import test from 'node:test';
import assert from 'node:assert/strict';
import { expireNotice, fourGateReview, latencyBudget, launchRunbook, mobileShot, releaseDiff, statusBanner, usabilityFinding } from '../src/bannerGate.js';
test('a finished notice is resolved', () => { assert.equal(expireNotice({ done: true }).open, false); });
test('a banner needs text and an end', () => { assert.equal(statusBanner({ text: 'Late' }).shown, false); });
test('a launch step needs an owner', () => { assert.equal(launchRunbook({ name: 'score' }).ok, false); });
test('a slow call misses the budget', () => { assert.equal(latencyBudget({ ms: 800, budget: 500 }).ok, false); });
test('a release names the risk', () => { assert.equal(releaseDiff({ files: 2, risk: 'low' }).ok, true); });
test('four gates are due for review', () => { assert.equal(fourGateReview({ gates: 4 }).due, true); });
test('a usability finding records the result', () => { assert.equal(usabilityFinding({ step: 'save' }).ok, false); });
test('a mobile shot is 390 wide', () => { assert.equal(mobileShot({ width: 390 }).ok, true); });
