import test from 'node:test';
import assert from 'node:assert/strict';
import { colorIndependent, discoverable, eligibilityWhy, emptyState, incidentTree, knownIssue, manualScore, topError } from '../src/emptyGate.js';
test('an empty page has one action', () => { assert.equal(emptyState({ empty: true }).ok, false); });
test('a workflow shows its path', () => { assert.equal(discoverable({ label: 'Score', path: '/score' }).ok, true); });
test('status is named in words', () => { assert.equal(colorIndependent({ word: 'blocked' }).ok, true); });
test('an outage has a hand entry step', () => { assert.match(manualScore({ step: 'Enter the score by hand.' }).text, /hand/); });
test('an incident names the first response', () => { assert.equal(incidentTree({ name: 'score', first: 'Retry.' }).ok, true); });
test('a top error names the workflow', () => { assert.match(topError({ workflow: 'prizes', count: 4 }).text, /prizes/); });
test('a known issue is shown when it is not blocking', () => { assert.equal(knownIssue({ title: 'Teams loading', blocking: false }).shown, true); });
test('eligibility says which requirement is missing', () => { assert.match(eligibilityWhy({ paid: false, available: true }).text, /Payment/); });
