import test from 'node:test';
import assert from 'node:assert/strict';
import { agingReview, bindingInventory, destructiveAction, factSource, gateDefect, reportEvidence, sessionLane, workflowHealth } from '../src/factGate.js';
test('unrelated messages stay private', () => { assert.equal(reportEvidence({ id: 'r1', private: true }).ok, false); });
test('a session lane matches its host', () => { assert.equal(sessionLane({ lane: 'dru', host: 'gamma' }).ok, false); });
test('a fact names its source', () => { assert.equal(factSource({ source: 'standings' }).ok, true); });
test('a delete says what it removes', () => { assert.equal(destructiveAction({}).ok, false); });
test('a ninety day feature is due for review', () => { assert.equal(agingReview({ days: 90 }).due, true); });
test('a blocking defect fails the gate', () => { assert.equal(gateDefect({ blocking: true }).fails, true); });
test('an environment lists its bindings', () => { assert.equal(bindingInventory({ name: 'dru', bindings: ['DB'] }).ok, true); });
test('workflow health names a known workflow', () => { assert.equal(workflowHealth({ workflow: 'score', status: 'ok' }).ok, true); });
