import test from 'node:test';
import assert from 'node:assert/strict';
import { adminCorrection, cleanRoom, messageRoom, opsRecovery, postseasonLineup, prizeConfig, releaseRecommendation, standingsAfterFinal } from '../src/gateReady2.js';
test('standings ignore an open match', () => { assert.equal(standingsAfterFinal([{ final: false }]).ok, false); });
test('a correction needs both sides', () => { assert.equal(adminCorrection({ actor: 'Mina' }).ok, false); });
test('a message is direct, team, or league', () => { assert.equal(messageRoom('trade').ok, false); });
test('a prize names the amount', () => { assert.equal(prizeConfig({ name: 'Night', amount: 20 }).ok, true); });
test('postseason is four players with an anchor', () => { assert.equal(postseasonLineup({ players: ['a', 'b', 'c', 'd'], anchor: 'a' }).ok, true); });
test('recovery names the step', () => { assert.equal(opsRecovery({ name: 'score' }).ok, false); });
test('a trial needs two captains', () => { assert.equal(cleanRoom({ homeCaptain: 'Mina' }).ok, false); });
test('a failed trial does not recommend release', () => { assert.equal(releaseRecommendation({ passed: false }).go, false); });
