import test from 'node:test';
import assert from 'node:assert/strict';
import { chatRoom, mobileShot, opsHub, playerSearch, rackLedger, recoveryTarget, rulesGuide, tddEvidence } from '../src/ledgerGate.js';
test('a mobile shot is 390 and names the gate', () => { assert.equal(mobileShot({ width: 390, gate: 'score' }).ok, true); });
test('recovery names the point and the time', () => { assert.equal(recoveryTarget({ point: 'night', time: '1h' }).ok, true); });
test('TDD shows red, then green', () => { assert.equal(tddEvidence({ red: true, green: false }).ok, false); });
test('a rack names the race and the winner', () => { assert.equal(rackLedger({ race: '1' }).ok, false); });
test('chat is direct, team, or general', () => { assert.equal(chatRoom('trade').ok, false); });
test('player search needs a name', () => { assert.equal(playerSearch({}).ok, false); });
test('a rule has a short title', () => { assert.equal(rulesGuide({ title: 'Lineup', short: 'Three players.' }).ok, true); });
test('the hub shows health and exceptions', () => { assert.equal(opsHub({ health: true }).ok, false); });
