import test from 'node:test';
import assert from 'node:assert/strict';
import { allowlist, contrastState, diagnosticBundle, failedGate, messageScroll, personaEvidence, releaseManifest, scheduleAfterSeason } from '../src/liveOps.js';
test('the allowlist names the host', () => { assert.equal(allowlist('dru.fremontderby.com').ok, true); });
test('evidence needs a persona, a step, and a result', () => { assert.equal(personaEvidence({ persona: 'captain', step: 'lineup', result: 'pass' }).ok, true); });
test('a manifest needs a name and a SHA', () => { assert.equal(releaseManifest({ name: 'schedule', sha: 'abc' }).approved, true); });
test('a failed gate names the test', () => { assert.match(failedGate({ gate: 'score', test: 'rack' }).text, /rack/); });
test('menu contrast has three states', () => { assert.equal(contrastState('trade').ok, false); });
test('messages can scroll', () => { assert.equal(messageScroll({ overflow: 'hidden' }).ok, false); });
test('schedule waits for a season', () => { assert.equal(scheduleAfterSeason({}).ok, false); });
test('a diagnostic bundle needs lane, SHA, and error', () => { assert.equal(diagnosticBundle({ lane: 'dru', sha: 'abc', error: 'html' }).ok, true); });
