import test from 'node:test';
import assert from 'node:assert/strict';
import { bootstrapStatus, nextAction, nightStep, onionLayer, personaMission, serviceDown, supportInfra, triageLabel } from '../src/nightGate.js';
test('a night step needs an owner', () => { assert.equal(nightStep({ name: 'score', owner: 'captain' }).ok, true); });
test('triage links a defect', () => { assert.match(triageLabel({ label: 'bug', issue: 12 }).text, /#12/); });
test('a mission needs a task', () => { assert.equal(personaMission({ persona: 'player' }).ready, false); });
test('bootstrap 405 is blocked', () => { assert.equal(bootstrapStatus({ status: 405 }).ok, false); });
test('a page has one next action', () => { assert.equal(nextAction({ actions: ['Save', 'Delete'] }).ok, false); });
test('the onion starts at the baseline', () => { assert.equal(onionLayer({ gate: 0 }).ok, true); });
test('support needs evidence', () => { assert.equal(supportInfra({ evidence: 'shot', persona: 'captain' }).ok, true); });
test('a down service can be retried', () => { assert.equal(serviceDown('').retry, true); });
