import test from 'node:test';
import assert from 'node:assert/strict';
import { noticeAction, opsHealth, payoutSummary, playerDetail, playerSearch, rackEntry, seasonLifecycle, seasonSetup } from '../src/onionGate.js';
test('a rack needs a winner and a confirmation', () => { assert.equal(rackEntry({ winner: 'Owls' }).ok, false); });
test('a notice has one action', () => { assert.equal(noticeAction({ title: 'Score', action: 'Open' }).ok, true); });
test('player detail says eligibility', () => { assert.equal(playerDetail({ name: 'Eli' }).ok, false); });
test('a prize names the amount', () => { assert.equal(payoutSummary({ name: 'Night', amount: 20 }).ok, true); });
test('setup names the next step', () => { assert.equal(seasonSetup({ name: 'teams' }).ok, false); });
test('player search needs a name', () => { assert.equal(playerSearch({}).ok, false); });
test('ops health names the status', () => { assert.equal(opsHealth({ name: 'db', status: 'ok' }).ok, true); });
test('season status is one of four', () => { assert.equal(seasonLifecycle({ status: 'trade' }).ok, false); });
