import test from 'node:test';
import assert from 'node:assert/strict';
import { antiSpam, hardDelete, hesitation, humanIntervention, operatorRunbook, registrationDrop, ruleDecision, sharedShell } from '../src/opsGate.js';
test('an operator needs the product and the runbook', () => { assert.equal(operatorRunbook({ runbook: true }).ok, false); });
test('six messages slow down', () => { assert.equal(antiSpam({ count: 6 }).ok, false); });
test('history cannot be deleted', () => { assert.equal(hardDelete({ history: true }).allowed, false); });
test('a rule records the impact', () => { assert.equal(ruleDecision({ decision: 'lock', impact: 'lineup' }).ok, true); });
test('a human intervention says why', () => { assert.equal(humanIntervention({}).counted, false); });
test('a third attempt asks for the next action', () => { assert.equal(hesitation({ attempts: 3 }).flagged, true); });
test('an expired registration is dropped', () => { assert.equal(registrationDrop({ expired: true }).drop, true); });
test('the shell keeps nav and title', () => { assert.equal(sharedShell({ nav: true, title: 'Home' }).ok, true); });
