import test from 'node:test';
import assert from 'node:assert/strict';
import { convergenceGate, dateStatus, participationMatch, personaSelector, phoneFormat, profileRetest, qualification, statusTable } from '../src/polishGate.js';
test('Gamma review needs a peer', () => { assert.equal(convergenceGate({ lane: 'dru', sha: 'abc' }).ok, false); });
test('persona selector stays off production', () => { assert.equal(personaSelector({ lane: 'prod' }).ok, false); });
test('a phone is ten digits', () => { assert.equal(phoneFormat('2065550100').ok, true); });
test('qualification shows the match count', () => { assert.match(qualification({ matches: 1, needed: 3 }).text, /1 of 3/); });
test('a profile retest needs a human', () => { assert.equal(profileRetest({ sha: 'abc' }).ok, false); });
test('check-in matches eligibility', () => { assert.equal(participationMatch({ checkedIn: true, eligible: false }).ok, false); });
test('a date row names its status', () => { assert.equal(dateStatus({ date: '2026-10-01', status: 'in' }).ok, true); });
test('every status row is named', () => { assert.equal(statusTable([{ status: 'in' }, {}]).ok, false); });
