import test from 'node:test';
import assert from 'node:assert/strict';
import { buildRestore, deployCommand, publicBuild, rackAdvance, rootProfile, schemaIsolation, skinCatalog, workerStamp } from '../src/rackGate.js';
test('a rack win advances the score', () => { assert.equal(rackAdvance({ won: true, total: 2 }).total, 3); assert.equal(rackAdvance({ won: false }).unlocked, false); });
test('a catalog entry needs a name', () => { assert.equal(skinCatalog({ name: 'Owls', lane: 'dru' }).ok, true); });
test('a lane worker is not production', () => { assert.equal(workerStamp({ lane: 'production' }).ok, false); });
test('the DRU profile stays DRU', () => { assert.equal(rootProfile({ root: 'dru' }).ok, true); });
test('a deploy command names the lane', () => { assert.equal(deployCommand({ lane: 'dru', explicit: true }).ok, true); });
test('a non-prod schema is named', () => { assert.equal(schemaIsolation({ schema: 'dru' }).ok, true); assert.equal(schemaIsolation({ schema: 'prod' }).ok, false); });
test('a build must be routed', () => { assert.equal(buildRestore({ routed: false }).ok, false); });
test('a public PR cannot build', () => { assert.equal(publicBuild({ publicPr: true }).ok, false); });
