import test from 'node:test';
import assert from 'node:assert/strict';
import { cloneDrift, functionalSmoke, leagueAdmin, oneCaptain, onionPage, sharedShell, standingsMode, visibleState } from '../src/scopeGate.js';
test('an admin stays in their league', () => { assert.equal(leagueAdmin({ role: 'admin', league: 'a' }, 'b').ok, false); });
test('smoke needs data', () => { assert.equal(functionalSmoke({ data: false }).ok, false); });
test('the shell keeps nav and title', () => { assert.equal(sharedShell({ nav: true, title: 'Home' }).ok, true); });
test('staging drift is named', () => { assert.equal(cloneDrift({ staging: 'v2', prod: 'v1' }).drifted, true); });
test('standings mode is team or player', () => { assert.equal(standingsMode('team').ok, true); });
test('one captaincy at a time', () => { assert.equal(oneCaptain({ captainOf: ['a', 'b'] }).ok, false); });
test('an onion page names its task', () => { assert.equal(onionPage({ shell: true }).ok, false); });
test('state is shown in words', () => { assert.equal(visibleState({ label: 'team' }).ok, true); });
