import test from 'node:test';
import assert from 'node:assert/strict';
import { renderTeamsPage } from '../src/teamsPage.js';

test('teams page uses the signed-in session and human-readable team setup controls', () => {
  const html = renderTeamsPage();

  assert.match(html, /Fremont Derby Teams/);
  assert.match(html, /data-night-hub/);
  assert.match(html, /League night/);
  assert.match(html, /data-hub-lineup/);
  assert.match(html, /data-hub-availability/);
  assert.match(html, /data-hub-score/);
  assert.match(html, /data-hub-chat/);
  assert.match(html, /data-hub-manage/);
  assert.match(html, /Mark availability/);
  assert.match(html, /Score a match/);
  assert.match(html, /Roster & trades/);
  assert.match(html, /href="\/availability"/);
  assert.match(html, /href="\/scorecard"/);
  assert.match(html, /lineupRounds/);
  assert.match(html, /round\.opponentName/);
  assert.match(html, /\/lineup\?team=/);
  assert.match(html, /id="join-teams"/);
  assert.match(html, /data-season-select/);
  assert.match(html, /data-team-name/);
  assert.match(html, /data-create-team/);
  assert.doesNotMatch(html, /data-season-id/);
  assert.doesNotMatch(html, /data-token/);
  assert.doesNotMatch(html, />Season ID</i);
  assert.doesNotMatch(html, />Access token</i);
  assert.doesNotMatch(html, />Player ID</i);
  assert.match(html, /sessionStorage\.getItem\('fd\.accessToken'\)/);
  assert.match(html, /Choose a player/);
  assert.match(html, /data-refresh/);
  assert.match(html, /data-captain-teams/);
  assert.match(html, /data-invitations/);
  assert.match(html, /\/api\/me\/teams/);
  assert.match(html, /\/api\/seasons\//);
  assert.match(html, /\/api\/teams\//);
  assert.match(html, /\/api\/team-invitations\//);
  assert.match(html, /\/api\/team-memberships\//);
  assert.match(html, /\/messages\?team=/);
});
