export function renderAdminSeasonTeamsPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Fremont Derby · Season teams</title>
  <style>
    :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#0c1210;color:#f6f1e7;--panel:#152019;--line:#32473a;--muted:#a8b7ae;--green:#43bd7d;--gold:#e6bd46;--red:#e36c61}*{box-sizing:border-box}body{margin:0;background:#0c1210;color:#f6f1e7}.app{width:min(760px,100%);margin:auto;padding:14px}.head{display:grid;gap:7px;margin-bottom:14px}.head h1{margin:0;font-size:clamp(1.55rem,7vw,2.25rem)}.head p{margin:0;color:var(--muted);line-height:1.4}.toolbar{display:grid;gap:10px;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--panel)}label{display:grid;gap:5px;color:var(--muted);font-size:.76rem;font-weight:850}select,input,button{font:inherit}select,input{width:100%;min-height:46px;border:1px solid var(--line);border-radius:10px;background:#0c1410;color:#fff;padding:0 12px}.capacity{display:flex;justify-content:space-between;gap:8px;align-items:baseline}.capacity strong{font-size:1.35rem}.capacity span{color:var(--muted);font-size:.78rem}.tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.tab,.add{min-height:48px;border-radius:11px;border:1px solid var(--line);font-weight:950;cursor:pointer}.tab{background:#151d18;color:#e7eee9}.tab[aria-pressed=true]{background:var(--gold);color:#151003;border-color:var(--gold)}.list{display:grid;gap:9px}.card{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;border:1px solid var(--line);border-radius:14px;background:var(--panel);padding:12px}.card h2{font-size:1rem;margin:0 0 4px}.meta{color:var(--muted);font-size:.75rem;line-height:1.45}.add{background:var(--green);color:#07110b;border-color:var(--green);padding:0 14px}.add:disabled,.tab:disabled,select:disabled,input:disabled{opacity:.5;cursor:not-allowed}.state{min-height:28px;margin-top:10px;color:var(--muted);font-size:.82rem}.state[data-tone=error]{color:#ffb5ae}.state[data-tone=ok]{color:#a7ebc1}.empty{padding:24px 12px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:14px}.links{display:flex;flex-wrap:wrap;gap:10px;margin-top:14px}.links a{color:#bcebd0;font-weight:850;text-decoration:none}@media(max-width:520px){.app{padding:10px}.card{grid-template-columns:1fr}.add{width:100%}.tabs{gap:5px}.tab{font-size:.78rem;padding:4px}}
  </style>
</head>
<body>
  <main class="app">
    <header class="head"><h1>Season teams</h1><p>Add returning or new teams without copying old rosters. Historical seasons stay unchanged.</p></header>
    <section class="toolbar" aria-label="Season team controls">
      <label>Season<select data-season disabled><option>Loading seasons…</option></select></label>
      <div class="capacity"><strong data-capacity>—</strong><span data-open-slots>Loading team slots…</span></div>
      <label>Find a team<input data-search type="search" placeholder="Team or captain name" disabled /></label>
    </section>
    <nav class="tabs" aria-label="Team views"><button class="tab" data-tab="returning" aria-pressed="true">Returning</button><button class="tab" data-tab="new" aria-pressed="false">New</button><button class="tab" data-tab="in_season" aria-pressed="false">In season</button></nav>
    <div class="list" data-list></div><div class="state" data-state aria-live="polite"></div>
    <div class="links"><a href="/season-setup">Season setup</a><a href="/admin/operations">Operations</a></div>
  </main>
  <script>
    const seasonSelect=document.querySelector('[data-season]');const search=document.querySelector('[data-search]');const list=document.querySelector('[data-list]');const state=document.querySelector('[data-state]');const capacity=document.querySelector('[data-capacity]');const openSlots=document.querySelector('[data-open-slots]');const tabs=[...document.querySelectorAll('[data-tab]')];let seasons=[];let teams=[];let registration=null;let activeTab='returning';
    function token(){return sessionStorage.getItem('fd.accessToken')||''}function setState(message,tone=''){state.textContent=message;state.dataset.tone=tone}async function api(path,options={}){const auth=token();if(!auth)throw new Error('Sign in with Google from Profile to manage league teams.');const response=await fetch(path,{...options,headers:{authorization:'Bearer '+auth,'content-type':'application/json',...(options.headers||{})}});const text=await response.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={error:text}}if(response.status===401)sessionStorage.removeItem('fd.accessToken');if(!response.ok)throw new Error(body.error||'Request failed');return body}function selectedSeasonId(){return seasonSelect.value||''}function normalized(row,key){return row[key]??row[key.replace(/[A-Z]/g,m=>'_'+m.toLowerCase())]}
    function renderCapacity(){const counts=registration?.counts||{};const used=Number(counts.occupiedSlots??0);const total=Number(registration?.teamCapacity??0);capacity.textContent=total?used+' of '+total+' teams':'—';openSlots.textContent=total?Math.max(0,total-used)+' slot'+(total-used===1?'':'s')+' open':'No capacity loaded'}
    function context(row){const parts=[];const source=normalized(row,'sourceSeasonName');const captain=normalized(row,'captainDisplayName');const roster=Number(normalized(row,'activeRosterCount')||0);if(activeTab==='returning'&&source)parts.push('Last season: '+source);if(captain)parts.push('Captain: '+captain);else parts.push('Captain not assigned');parts.push(roster+' rostered');const status=normalized(row,'slotStatus');if(status)parts.push(status.replaceAll('_',' '));return parts.join(' · ')}
    function render(){const query=search.value.trim().toLowerCase();const filtered=teams.filter(row=>normalized(row,'candidateKind')===activeTab).filter(row=>{if(!query)return true;return [normalized(row,'teamName'),normalized(row,'captainDisplayName')].some(value=>String(value||'').toLowerCase().includes(query))});list.replaceChildren();if(!filtered.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=query?'No matching teams.':activeTab==='returning'?'No returning teams available to add.':activeTab==='new'?'No new teams waiting to be added.':'No teams are in this season yet.';list.append(empty);return}for(const row of filtered){const card=document.createElement('article');card.className='card';const copy=document.createElement('div');const title=document.createElement('h2');title.textContent=normalized(row,'teamName')||'Unnamed team';const meta=document.createElement('div');meta.className='meta';meta.textContent=context(row);copy.append(title,meta);card.append(copy);if(activeTab!=='in_season'){const button=document.createElement('button');button.className='add';button.type='button';button.textContent='Add to season';button.disabled=Number(registration?.counts?.availableSlots??0)<=0;button.addEventListener('click',()=>addTeam(row,button));card.append(button)}list.append(card)}}
    async function loadSeasons(){if(!token()){setState('Sign in with Google from Profile to manage league teams.','error');seasonSelect.innerHTML='<option>Sign in required</option>';return}const body=await api('/api/admin/seasons');seasons=body.seasons||[];seasonSelect.replaceChildren();for(const season of seasons){const option=document.createElement('option');option.value=season.id;option.textContent=season.name+' — '+season.status;seasonSelect.append(option)}const requested=new URLSearchParams(location.search).get('season');if(requested&&seasons.some(item=>item.id===requested))seasonSelect.value=requested;seasonSelect.disabled=!seasons.length;search.disabled=!seasons.length;if(seasons.length)await loadTeams();else setState('No seasons exist yet. Create one in Season setup.','error')}
    async function loadTeams(){setState('Loading teams…');const id=selectedSeasonId();if(!id)return;const body=await api('/api/admin/seasons/'+encodeURIComponent(id)+'/team-candidates');registration=body.registration||null;teams=body.teams||[];renderCapacity();render();setState('Ready','ok');const url=new URL(location.href);url.searchParams.set('season',id);history.replaceState({},'',url)}
    async function addTeam(row,button){const id=selectedSeasonId();const teamId=normalized(row,'teamId');button.disabled=true;setState('Adding '+normalized(row,'teamName')+'…');try{await api('/api/admin/seasons/'+encodeURIComponent(id)+'/teams/'+encodeURIComponent(teamId)+'/add',{method:'POST'});await loadTeams();setState(normalized(row,'teamName')+' added to the season.','ok')}catch(error){setState(error.message,'error');button.disabled=false}}
    for(const tab of tabs)tab.addEventListener('click',()=>{activeTab=tab.dataset.tab;for(const item of tabs)item.setAttribute('aria-pressed',String(item===tab));render()});search.addEventListener('input',render);seasonSelect.addEventListener('change',()=>loadTeams().catch(error=>setState(error.message,'error')));loadSeasons().catch(error=>setState(error.message,'error'));
  </script>
</body>
</html>`;
}
