/** Generated by scripts/stamp-deploy-identity.mjs — do not edit. */
export const DEPLOY_IDENTITY = {
  gitSha: "deadbeefcafebabe0123456789abcdef01234567",
  stampedAt: "2026-08-17T01:02:31.993Z",
};
