function assertRepository(repository, method) {
  if (!repository || typeof repository[method] !== 'function') throw new Error(`dual scoring repository must implement ${method}`);
}
function assertActor(actorUserId) { if (!actorUserId) throw new Error('actorUserId is required'); }
function assertPlayerMatchId(playerMatchId) { if (!playerMatchId) throw new Error('playerMatchId is required'); }
function assertScoringTeamId(scoringTeamId) { if (!scoringTeamId) throw new Error('scoringTeamId is required'); }
function normalizeWinnerSide(value) { if (!['A', 'B'].includes(value)) throw new Error('winnerSide must be A or B'); return value; }
function normalizeRackNumber(value) { const number = Number(value); if (!Number.isInteger(number) || number < 1) throw new Error('rackNumber must be a positive integer'); return number; }
function normalizeOpeningDiscipline(value) { const normalized = value === '8' ? '8-ball' : value === '9' ? '9-ball' : value; if (!['8-ball', '9-ball'].includes(normalized)) throw new Error('openingDiscipline must be 8-ball or 9-ball'); return normalized; }
function normalizeReason(value) { const reason = typeof value === 'string' ? value.trim() : ''; if (!reason) throw new Error('reason is required'); return reason; }
function normalizeResolvedRacks(value) { if (!Array.isArray(value) || value.length === 0) throw new Error('resolvedRacks must be a non-empty array'); return value; }
function assertScoringContext({ actorUserId, playerMatchId, scoringTeamId }) { assertActor(actorUserId); assertPlayerMatchId(playerMatchId); assertScoringTeamId(scoringTeamId); }
export async function getPlayerMatchScoreComparisonCommand(input, repository) { assertScoringContext(input); assertRepository(repository, 'getPlayerMatchScoreComparison'); return repository.getPlayerMatchScoreComparison(input); }
export async function setPlayerMatchOpeningDisciplineCommand({ actorUserId, playerMatchId, scoringTeamId, openingDiscipline }, repository) { assertScoringContext({ actorUserId, playerMatchId, scoringTeamId }); assertRepository(repository, 'setPlayerMatchOpeningDiscipline'); return repository.setPlayerMatchOpeningDiscipline({ actorUserId, playerMatchId, scoringTeamId, openingDiscipline: normalizeOpeningDiscipline(openingDiscipline) }); }
export async function recordPlayerMatchScoreRackCommand({ actorUserId, playerMatchId, scoringTeamId, winnerSide }, repository) { assertScoringContext({ actorUserId, playerMatchId, scoringTeamId }); assertRepository(repository, 'recordPlayerMatchScoreRack'); return repository.recordPlayerMatchScoreRack({ actorUserId, playerMatchId, scoringTeamId, winnerSide: normalizeWinnerSide(winnerSide) }); }
export async function updatePlayerMatchScoreRackCommand({ actorUserId, playerMatchId, scoringTeamId, rackNumber, winnerSide }, repository) { assertScoringContext({ actorUserId, playerMatchId, scoringTeamId }); assertRepository(repository, 'updatePlayerMatchScoreRack'); return repository.updatePlayerMatchScoreRack({ actorUserId, playerMatchId, scoringTeamId, rackNumber: normalizeRackNumber(rackNumber), winnerSide: normalizeWinnerSide(winnerSide) }); }
export async function undoPlayerMatchScoreRackCommand(input, repository) { assertScoringContext(input); assertRepository(repository, 'undoPlayerMatchScoreRack'); return repository.undoPlayerMatchScoreRack(input); }
export async function confirmPlayerMatchScoreCommand(input, repository) { assertScoringContext(input); assertRepository(repository, 'confirmPlayerMatchScore'); return repository.confirmPlayerMatchScore(input); }
export async function finalizeReconciledPlayerMatchCommand(input, repository) { assertScoringContext(input); assertRepository(repository, 'finalizeReconciledPlayerMatch'); return repository.finalizeReconciledPlayerMatch(input); }
export async function adminOverrideReconciledPlayerMatchCommand({ actorUserId, playerMatchId, reason, resolvedRacks }, repository) { assertActor(actorUserId); assertPlayerMatchId(playerMatchId); assertRepository(repository, 'adminOverrideReconciledPlayerMatch'); return repository.adminOverrideReconciledPlayerMatch({ actorUserId, playerMatchId, reason: normalizeReason(reason), resolvedRacks: normalizeResolvedRacks(resolvedRacks) }); }
