export async function enhanceFinishedScheduleBreakdown(response) {
  const contentType = response.headers.get('content-type') || '';
  if (!contentType.includes('text/html')) return response;
  let html = await response.text();
  if (!html.includes('data-schedule-groups')) return new Response(html, response);

  const css = `<style>
    .fd-finished-breakdown{display:grid;gap:8px;padding:10px 0 2px;border-top:1px solid #eceae4}.fd-finished-breakdown__points{display:flex;justify-content:space-between;align-items:center;gap:12px;font-weight:950}.fd-finished-breakdown__points strong{font-size:1.05rem;color:#075f3a}.fd-finished-breakdown__rows{display:grid;gap:6px}.fd-finished-breakdown__row{display:grid;grid-template-columns:minmax(0,1fr) auto auto minmax(0,1fr);gap:8px;align-items:center;padding:7px 8px;border-radius:9px;background:#f7f5ef}.fd-finished-breakdown__row span:nth-child(4){text-align:right}.fd-finished-breakdown__score{min-width:26px;text-align:center;font-weight:950;font-variant-numeric:tabular-nums}@media(max-width:520px){.fd-finished-breakdown__row{gap:6px;padding:6px}.fd-finished-breakdown__row span:first-child,.fd-finished-breakdown__row span:last-child{font-size:.82rem}}
  </style>`;
  const script = `<script>
  (()=>{const groups=document.querySelector('[data-schedule-groups]');const season=document.querySelector('[data-season-select]');const round=document.querySelector('[data-round-select]');if(!groups||!season)return;let seq=0;const clean=v=>String(v||'');function finished(m){return ['finalized','corrected'].includes(clean(m.status))}function make(match){const box=document.createElement('section');box.className='fd-finished-breakdown';box.dataset.finishedBreakdown='true';const points=document.createElement('div');points.className='fd-finished-breakdown__points';const label=document.createElement('span');label.textContent='Team points';const score=document.createElement('strong');score.textContent=(match.teamAScore??0)+' – '+(match.teamBScore??0);points.append(label,score);const rows=document.createElement('div');rows.className='fd-finished-breakdown__rows';for(const result of match.playerResults||[]){const row=document.createElement('div');row.className='fd-finished-breakdown__row';for(const value of [result.playerAName,result.scoreA,result.scoreB,result.playerBName]){const span=document.createElement('span');span.textContent=value??'—';if(value===result.scoreA||value===result.scoreB)span.className='fd-finished-breakdown__score';row.append(span)}rows.append(row)}box.append(points,rows);return box}async function apply(){const id=++seq;if(!season.value)return;let response;try{response=await fetch('/api/seasons/'+encodeURIComponent(season.value)+'/schedule')}catch{return}if(id!==seq||!response.ok)return;let body;try{body=await response.json()}catch{return}let matches=(body.rounds||[]).flatMap(r=>!round||!round.value||r.roundId===round.value?(r.matches||[]):[]);const cards=[...groups.querySelectorAll('.fd-schedule-match')];cards.forEach((card,index)=>{card.querySelector('[data-finished-breakdown]')?.remove();const match=matches[index];if(!match||!finished(match)||!(match.playerResults||[]).length)return;const details=card.querySelector('.fd-schedule-match__details');card.insertBefore(make(match),details||null)})}let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(apply,25)}).observe(groups,{childList:true,subtree:true});season.addEventListener('change',()=>setTimeout(apply,50));round?.addEventListener('change',()=>setTimeout(apply,50));setTimeout(apply,50)})();
  </script>`;
  html = html.replace('</head>', `${css}</head>`).replace('</body>', `${script}</body>`);
  return new Response(html,{status:response.status,statusText:response.statusText,headers:new Headers(response.headers)});
}
