export {
  serviceName,
  versionMetadata,
  jsonResponse,
  readJsonBody,
  clientErrorMessage,
  statusForError,
  renderLandingPage,
} from './indexShared.js';
export {
  handlePublishScheduleRequest,
  handleCreateSeasonSetupRequest,
  handleListAdminSeasonsRequest,
  handleGetSeasonSetupRequest,
  handleUpdateSeasonSetupRequest,
  handleGetOwnProfileRequest,
  handleSaveOwnProfileRequest,
  handleCreateTeamRequest,
  handleGetOwnTeamRegistrationRequest,
  handleWithdrawTeamApplicationRequest,
  handleRespondToReturningTeamSlotRequest,
  handleGetAdminSeasonRegistrationRequest,
  handleConfigureSeasonRegistrationRequest,
  handleReviewTeamApplicationRequest,
} from './indexHandlersA.js';
export {
  handleManageTeamSlotRequest,
  handleSeedReturningTeamSlotsRequest,
  handleListOwnTeamMembershipRequestsRequest,
  handleRequestTeamMembershipRequest,
  handleRespondToTeamMembershipRequest,
  handleCancelTeamMembershipRequest,
  handleListOwnTeamManagementRequest,
  handleInvitePlayerToTeamRequest,
  handleRespondToTeamInvitationRequest,
  handleCancelTeamInvitationRequest,
  handleRemoveTeamMemberRequest,
  handleRegisterFreeAgentRequest,
  handleSetFreeAgentAvailabilityRequest,
  handleListEligibleFreeAgentsRequest,
  handleSetRosterAvailabilityRequest,
} from './indexHandlersB.js';
export {
  handleListTeamRoundAvailabilityRequest,
  handleSubmitTeamLineupRequest,
  handleListVisibleTeamLineupsRequest,
  handleListPublicSeasonsRequest,
  handleListSeasonScheduleRequest,
  handleListTeamStandingsRequest,
  handleListIndividualStandingsRequest,
  handleGetSeasonPrizeSummaryRequest,
  handleConfigureSeasonPrizesRequest,
  handleFinalizeSeasonPrizePayoutsRequest,
  handleGetPlayerMatchScorecardRequest,
  handleRecordPlayerMatchRackRequest,
  handleUndoPlayerMatchRackRequest,
  handleFinalizePlayerMatchRequest,
  handleCorrectPlayerMatchRequest,
} from './indexHandlersC.js';

export { default } from './indexRouter.js';
