export const surfaceLines = {
  2311: 'Recent surveys are counted for the admin.',
  2310: 'Survey results stay on the admin page.',
  2308: 'A message names the recipient and the body.',
  2307: 'Eligibility names payment and the waiver.',
  2306: 'Standings name the place.',
  2303: 'A mission batch is six in a row.',
  2301: 'The runner finishes on a phone frame.',
  2293: 'Abort stays on the mission.',
  2290: 'A stuck mission goes back to the schedule.',
  2286: 'Test Drive is not the player path.',
  2284: 'Submit waits until every rack is done.',
  2281: 'Preview is not the tester path.',
  2279: 'Launch says start the mission.',
  2278: 'The mission shows the task.',
  2277: 'Captain transfer names a different person.',
  2276: 'Adding a player names the team.',
  2275: 'Availability is in, out, or maybe.',
  2274: 'The next match names the opponent.',
  2272: 'A campaign needs a persona and a mission.',
  2271: 'The campaign has a name.',
  2270: 'A replay names what changed.',
  2269: 'Ranking stays in shadow.',
  2268: 'A dataset row cannot hold a secret.',
  2267: 'A cluster counts its items.',
  2266: 'Triage links the defect.',
  2265: 'The explorer names the run.',
  2264: 'A client error stays public.',
  2262: 'Telemetry cannot hold a phone.',
  2259: 'The scorecard names the rack step.',
  2258: 'The validation loop names the round.',
  2256: 'A rack is named before the score.',
  2254: 'The selected score is named.',
  2249: 'A dispute is not the race result.',
  2247: 'An outside tap closes the menu and keeps the dock.',
  2228: 'A finished rack cannot stay open.',
  2184: 'Scorecard validation needs both teams.',
  2181: 'A finished match says match complete.',
  2173: 'A failed public check names the page.',
  2170: 'The live score is the one score on the card.',
  2168: 'Undo removes the last rack.',
  2165: 'The selected scoring control stays visible.',
  2163: 'A lineup edit unsubmits the lineup.',
  2158: 'A DRU branch targets fremontderby-dru.',
  2156: 'The next peel names the page.',
  1967: 'Lineup status is one sentence on a phone.',
  1963: 'Lineup status names both teams.',
  1955: 'Lineup stays editable until both captains submit.',
  1890: 'A skin needs a name and a lane.',
  1887: 'A page has one next action.',
  1783: 'A playoff match needs both teams.',
};
export function surfaceLine(card) {
  return { text: surfaceLines[card] || 'This step is not ready.' };
}
