import { createMatch, raceTargets, recordRack } from '../domain/match.js';

const fixture = {
  players: { A: 'Maya Example', B: 'Eli Example' },
  ratings: { A: 525, B: 475 },
  chart: [{ maxDiff: 49, strongerTo: 5, weakerTo: 5 }, { maxDiff: 99, strongerTo: 5, weakerTo: 4 }, { maxDiff: 9999, strongerTo: 6, weakerTo: 4 }],
  openingBlockLength: 3,
  openingDiscipline: '8-ball',
};

function clientDomainSource() {
  return `const raceTargets = ${raceTargets.toString()};\nconst createMatch = ${createMatch.toString()};\nconst recordRack = ${recordRack.toString()};`;
}

export function renderPlayerSandboxPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <title>Player Sandbox · Fremont Derby</title>
  <style>
    :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#101313;color:#f6f1e7;--panel:#1b1f1e;--line:#38413e;--muted:#aeb8b3;--green:#2fa972;--gold:#d8ad3f;--red:#d45b50;--blue:#4e83d6}*{box-sizing:border-box}body{margin:0;background:#101313}.app{width:min(980px,100%);margin:auto;padding:14px}.sandbox{position:sticky;top:0;z-index:5;padding:9px 12px;background:#5a4100;color:#fff4cf;border:1px solid #94711b;border-radius:8px;font-weight:900}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:14px 0}.muted{color:var(--muted)}a{color:#a9d8bc}.panel{border:1px solid var(--line);border-radius:8px;background:var(--panel);padding:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.players{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.player{border-top:4px solid var(--green)}.player.b{border-top-color:var(--blue)}h1,h2,h3{margin:0}.score{font-size:3.4rem;font-weight:950}.actions{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:10px}button{min-height:46px;border:1px solid transparent;border-radius:8px;font:inherit;font-weight:850;cursor:pointer}.a{background:var(--green)}.bbtn{background:var(--blue)}.ghost{background:transparent;color:#fff;border-color:var(--line)}.gold{background:var(--gold)}.danger{background:var(--red)}button:disabled{opacity:.45;cursor:not-allowed}.reconcile{margin-top:12px}.reconcile[data-state=mismatch]{border-color:var(--red)}.reconcile[data-state=match]{border-color:var(--green)}.history{margin-top:12px}.rack{display:grid;grid-template-columns:54px 1fr 1fr;gap:8px;padding:8px;border-bottom:1px solid var(--line)}.rack.bad{background:#351b19}.rack:last-child{border-bottom:0}.tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.tabs button.active{outline:3px solid var(--gold)}.auth{margin-top:12px}.final{font-weight:900;color:#9ee5bd}.warning{color:#ffc0b9}.feedback{margin-top:12px}.feedback textarea{width:100%;min-height:100px;margin-top:10px;padding:10px;border:1px solid var(--line);border-radius:8px;background:#101313;color:#fff;font:inherit;resize:vertical}.feedback-meta{margin-top:8px;font-size:.9rem}.feedback-status{min-height:1.25em;margin-top:8px;color:#9ee5bd}@media(max-width:700px){.grid,.players,.actions{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
  </style>
</head>
<body><main class="app">
  <div class="sandbox">SANDBOX · PRACTICE ONLY · NEVER AFFECTS LEAGUE RECORDS</div>
  <header class="top"><div><h1>Player scoring practice</h1><div class="muted">Practice both phones, including intentional mismatches and reconciliation.</div></div><a href="/demo">View demo season</a></header>
  <section class="panel auth" data-auth-note></section>
  <section class="panel" style="margin-top:12px"><h3>Whose phone are you practicing?</h3><div class="tabs"><button class="a active" data-perspective="A">Maya's phone</button><button class="bbtn" data-perspective="B">Eli's phone</button></div><div class="muted" style="margin-top:8px">Switch phones to enter each player's score independently. Try recording different winners to see the mismatch state.</div></section>
  <section class="players">
    <article class="panel player"><h2>Maya Example</h2><div class="muted">525 · <span data-race-a></span></div><div class="score" data-score-a>0</div></article>
    <article class="panel player b"><h2>Eli Example</h2><div class="muted">475 · <span data-race-b></span></div><div class="score" data-score-b>0</div></article>
  </section>
  <section class="panel reconcile" data-reconcile><h3 data-reconcile-title></h3><div class="muted" data-reconcile-detail></div></section>
  <section class="panel" style="margin-top:12px"><div class="muted">Current phone: <strong data-phone></strong> · discipline: <strong data-discipline></strong></div><div class="actions"><button class="a" data-win-a>Maya wins rack</button><button class="bbtn" data-win-b>Eli wins rack</button><button class="ghost" data-undo>Undo my rack</button></div><div class="actions"><button class="gold" data-confirm>Confirm my score</button><button class="danger" data-finalize>Finalize practice match</button><button class="ghost" data-reset>Reset sandbox</button></div></section>
  <section class="grid history"><article class="panel"><h3>Maya submission</h3><div class="muted" data-confirm-a></div><div data-racks-a></div></article><article class="panel"><h3>Eli submission</h3><div class="muted" data-confirm-b></div><div data-racks-b></div></article></section>
  <section class="panel feedback"><h3>Tell us what was confusing</h3><div class="muted">This practice-only feedback is stored separately from competitive records. The sandbox automatically captures where you were in the workflow.</div><textarea maxlength="1000" placeholder="What worked, what did not, or what would make league night easier?" data-feedback-text></textarea><div class="feedback-meta muted" data-feedback-context></div><div class="actions"><button class="gold" data-feedback-save>Save feedback</button><button class="ghost" data-feedback-clear>Clear saved feedback</button></div><div class="feedback-status" data-feedback-status aria-live="polite"></div></section>
</main><script>
${clientDomainSource()}
const fixture=${JSON.stringify(fixture)};const storageKey='fd.playerSandbox.v1';const feedbackKey='fd.sandboxFeedback.player.v1';let perspective='A';
function fresh(){const base={ratingA:fixture.ratings.A,ratingB:fixture.ratings.B,chart:fixture.chart,openingBlockLength:fixture.openingBlockLength,lagWinner:'A',lagChoice:'break',openingDiscipline:fixture.openingDiscipline};return{A:createMatch(base),B:createMatch(base),confirmed:{A:false,B:false},finalized:false}}
function load(){try{return JSON.parse(sessionStorage.getItem(storageKey))||fresh()}catch{return fresh()}}let state=load();
function save(){sessionStorage.setItem(storageKey,JSON.stringify(state))}function history(side){return state[side].racks}function equal(){const a=history('A'),b=history('B');return a.length>0&&a.length===b.length&&a.every((r,i)=>r.winner===b[i].winner&&r.discipline===b[i].discipline)}function mismatch(){const a=history('A'),b=history('B'),n=Math.max(a.length,b.length);for(let i=0;i<n;i++){if(!a[i]||!b[i]||a[i].winner!==b[i].winner||a[i].discipline!==b[i].discipline)return i+1}return null}function ready(){return equal()&&state.confirmed.A&&state.confirmed.B&&Boolean(state.A.winner)&&Boolean(state.B.winner)}
function replay(racks){let next=createMatch({ratingA:fixture.ratings.A,ratingB:fixture.ratings.B,chart:fixture.chart,openingBlockLength:fixture.openingBlockLength,lagWinner:'A',lagChoice:'break',openingDiscipline:fixture.openingDiscipline});for(const rack of racks)next=recordRack(next,rack.winner);return next}
function rackRows(side){const bad=mismatch();const rows=history(side);if(!rows.length)return'<div class="muted" style="padding:10px 0">No racks recorded.</div>';return rows.map(r=>'<div class="rack '+(r.number===bad?'bad':'')+'"><span>#'+r.number+'</span><strong>'+fixture.players[r.winner]+'</strong><span>'+r.discipline+'</span></div>').join('')}
function feedbackContext(){const bad=mismatch();return{surface:'player-sandbox',path:location.pathname,perspective,phase:state.finalized?'finalized':bad?'mismatch':ready()?'ready-to-finalize':history(perspective).length?'scoring':'start',mismatchRack:bad,racksA:history('A').length,racksB:history('B').length,confirmedA:state.confirmed.A,confirmedB:state.confirmed.B,finalized:state.finalized,capturedAt:new Date().toISOString()}}
function renderFeedbackContext(){const context=feedbackContext();document.querySelector('[data-feedback-context]').textContent='Context: '+context.phase+' · '+fixture.players[perspective]+' · '+context.racksA+'/'+context.racksB+' racks entered'}
function render(){const signed=Boolean(sessionStorage.getItem('fd.accessToken'));const note=document.querySelector('[data-auth-note]');note.innerHTML=signed?'Signed in browser session detected. Practice state stays only in this tab.':'<span class="warning">Sign in with Google before player practice.</span> <a href="/profile">Continue with Google</a>';document.querySelectorAll('[data-perspective]').forEach(b=>b.classList.toggle('active',b.dataset.perspective===perspective));document.querySelector('[data-phone]').textContent=fixture.players[perspective];document.querySelector('[data-discipline]').textContent=state[perspective].currentDiscipline;document.querySelector('[data-race-a]').textContent='race to '+state.A.targets.a;document.querySelector('[data-race-b]').textContent='race to '+state.B.targets.b;document.querySelector('[data-score-a]').textContent=state[perspective].score.a;document.querySelector('[data-score-b]').textContent=state[perspective].score.b;document.querySelector('[data-racks-a]').innerHTML=rackRows('A');document.querySelector('[data-racks-b]').innerHTML=rackRows('B');document.querySelector('[data-confirm-a]').textContent=state.confirmed.A?'Confirmed':'Not confirmed';document.querySelector('[data-confirm-b]').textContent=state.confirmed.B?'Confirmed':'Not confirmed';const rec=document.querySelector('[data-reconcile]'),title=document.querySelector('[data-reconcile-title]'),detail=document.querySelector('[data-reconcile-detail]');const bad=mismatch();if(state.finalized){rec.dataset.state='match';title.textContent='Practice match finalized';detail.innerHTML='<span class="final">Success. Nothing was written to Fremont Derby competitive data.</span>'}else if(equal()){rec.dataset.state='match';title.textContent=state.confirmed.A&&state.confirmed.B?'Scores match and both players confirmed.':'Scores match.';detail.textContent=ready()?'Ready to finalize.':'Both players must finish the race and confirm.'}else{rec.dataset.state='mismatch';title.textContent=bad?'Mismatch at rack '+bad+'.':'Enter both score histories.';detail.textContent='Switch phones, undo/correct the differing submission, then confirm both.'}const blocked=!signed||state.finalized||state.confirmed[perspective]||Boolean(state[perspective].winner);document.querySelector('[data-win-a]').disabled=blocked;document.querySelector('[data-win-b]').disabled=blocked;document.querySelector('[data-undo]').disabled=!signed||state.finalized||state.confirmed[perspective]||!history(perspective).length;document.querySelector('[data-confirm]').disabled=!signed||state.finalized||state.confirmed[perspective]||!state[perspective].winner;document.querySelector('[data-finalize]').disabled=!signed||state.finalized||!ready();renderFeedbackContext()}
function record(side){state[perspective]=recordRack(state[perspective],side);state.confirmed[perspective]=false;save();render()}function undo(){const racks=history(perspective).slice(0,-1);state[perspective]=replay(racks);state.confirmed[perspective]=false;save();render()}
function loadFeedback(){try{return JSON.parse(sessionStorage.getItem(feedbackKey))}catch{return null}}const existingFeedback=loadFeedback();if(existingFeedback?.comment)document.querySelector('[data-feedback-text]').value=existingFeedback.comment;
document.querySelectorAll('[data-perspective]').forEach(b=>b.onclick=()=>{perspective=b.dataset.perspective;render()});document.querySelector('[data-win-a]').onclick=()=>record('A');document.querySelector('[data-win-b]').onclick=()=>record('B');document.querySelector('[data-undo]').onclick=undo;document.querySelector('[data-confirm]').onclick=()=>{state.confirmed[perspective]=true;save();render()};document.querySelector('[data-finalize]').onclick=()=>{if(!ready())return;state.finalized=true;save();render()};document.querySelector('[data-reset]').onclick=()=>{state=fresh();save();render()};document.querySelector('[data-feedback-save]').onclick=()=>{const comment=document.querySelector('[data-feedback-text]').value.trim();const status=document.querySelector('[data-feedback-status]');if(!comment){status.textContent='Add a comment before saving feedback.';return}const entry={comment,context:feedbackContext()};sessionStorage.setItem(feedbackKey,JSON.stringify(entry));status.textContent='Feedback saved in this sandbox session. Admin review submission is the next isolated persistence slice.'};document.querySelector('[data-feedback-clear]').onclick=()=>{sessionStorage.removeItem(feedbackKey);document.querySelector('[data-feedback-text]').value='';document.querySelector('[data-feedback-status]').textContent='Saved feedback cleared.'};render();
</script></body></html>`;
}
