export const sharedRackLedgerScorecardControllerSource = String.raw`
  (function(){
    const adapter=window.fdRackLedgerAdapter;
    if(!adapter)throw new Error('Rack ledger scoring adapter is required');
    const statusEl=document.querySelector('[data-status]');const rackAButton=document.querySelector('[data-rack-a]');const rackBButton=document.querySelector('[data-rack-b]');const addRackButton=document.querySelector('[data-add-rack]');const winnerPicker=document.querySelector('[data-winner-picker]');const undoButton=document.querySelector('[data-undo]');const confirmButton=document.querySelector('[data-confirm]');const finalizeButton=document.querySelector('[data-finalize]');const openingSetup=document.querySelector('[data-opening-setup]');const openingButtons=[...document.querySelectorAll('[data-opening]')];const openingNote=document.querySelector('[data-opening-note]');const ledger=document.querySelector('[data-ledger]');const ledgerScroll=document.querySelector('[data-ledger-scroll]');const reconcileEl=document.querySelector('[data-reconcile]');const editPanel=document.querySelector('[data-edit-panel]');const editClose=document.querySelector('[data-edit-close]');const editResultButtons=[...document.querySelectorAll('[data-edit-result]')];const errorPopup=document.querySelector('[data-error]');const perspectiveEl=document.querySelector('[data-perspective]');const perspectiveButtons=[...document.querySelectorAll('[data-perspective-side]')];
    let currentScorecard=null;let currentComparison=null;let currentContext=null;let refreshTimer=null;let editingRackNumber=null;let ledgerRestoreLeft=null;let lastOwnSignature=null;let scoringTeamId=adapter.scoringTeamId();let scoringTeamName=adapter.scoringTeamName();
    function setStatus(message,tone){statusEl.textContent=message;statusEl.dataset.tone=tone||''}
    function setText(selector,value){const node=document.querySelector(selector);if(node)node.textContent=value==null||value===''?'–':String(value)}
    function showError(message){document.querySelector('[data-error-message]').textContent=message;errorPopup.dataset.open='true';clearTimeout(showError.timer);showError.timer=setTimeout(()=>{errorPopup.dataset.open='false'},6500)}
    function ratingText(rating,status){return[rating||'Unrated',status||'unverified'].join(' · ')}
    function sideName(side){if(!currentScorecard)return side;return side==='A'?currentScorecard.player_a_display_name:currentScorecard.player_b_display_name}
    function oppositeSide(side){return side==='A'?'B':'A'}
    function oppositeGame(game){return game==='9-ball'?'8-ball':'9-ball'}
    function gameForRack(number){if(!currentScorecard)return'–';return Number(number)<=Number(currentScorecard.opening_block_length||3)?currentScorecard.opening_discipline:oppositeGame(currentScorecard.opening_discipline)}
    function winnerSide(rack){return rack&&(rack.winnerSide||rack.winner_side)||null}
    function rackGame(rack,number){return rack&&rack.discipline||gameForRack(number)}
    function renderOpeningChoice(selected,locked){openingSetup.dataset.locked=String(locked);for(const button of openingButtons){button.setAttribute('aria-pressed',String(button.dataset.opening===selected));button.disabled=locked}openingNote.textContent=locked?'Order locked after rack 1 · '+(selected==='9-ball'?'9-ball first':'8-ball first'):'Choose before rack 1. Racks 1–3 use this game.';setText('[data-detail-opening]',selected==='9-ball'?'9-ball first':'8-ball first')}
    function rackState(own,opponent,number){if(!own&&!opponent)return'unplayed';if(!own||!opponent)return'pending';return winnerSide(own)===winnerSide(opponent)&&rackGame(own,number)===rackGame(opponent,number)?'matched':'mismatch'}
    function reconciledScore(comparison){let a=0,b=0;const own=comparison.own_racks||[];const opponent=comparison.opponent_racks||[];const count=Math.max(own.length,opponent.length);for(let i=0;i<count;i+=1){if(rackState(own[i],opponent[i],i+1)!=='matched')continue;const side=winnerSide(own[i]);if(side==='A')a+=1;if(side==='B')b+=1}return[a,b]}
    function trackerSide(){return currentComparison?.tracker_player_id===currentScorecard?.player_a_id?'A':'B'}
    function rowHistoryForPlayer(playerId){const own=currentComparison?.own_racks||[];const opponent=currentComparison?.opponent_racks||[];return currentComparison?.tracker_player_id===playerId?own:opponent}
    function cellValue(rack,playerSide){if(!rack)return'—';return winnerSide(rack)===playerSide?'W':'L'}
    function appendCell(row,rack,playerSide,state,number,name,editable){const cell=document.createElement('td');cell.className='submission';const value=cellValue(rack,playerSide);const canAnswerPending=editable&&!rack&&state==='pending';cell.dataset.value=value;cell.dataset.state=state;cell.setAttribute('aria-label','Rack '+number+', '+gameForRack(number)+', '+name+': '+(value==='—'?'no submission':value==='W'?'win':'loss')+', '+state);if(editable&&(rack||canAnswerPending)){const button=document.createElement('button');button.className='rack-edit';button.type='button';button.textContent=rack?value:'+';button.dataset.editRack=String(number);button.dataset.pending=String(canAnswerPending);button.setAttribute('aria-label',canAnswerPending?'Answer rack '+number+' waiting for your team':'Edit '+name+' rack '+number+', currently '+(value==='W'?'win':'loss'));cell.append(button)}else{cell.textContent=value}row.append(cell)}
    function appendStatusCell(row,state,number){const cell=document.createElement('td');cell.className='rack-status';cell.dataset.state=state;cell.textContent=state==='matched'?'✓':state==='mismatch'?'⚠':state==='pending'?'…':'—';cell.setAttribute('aria-label','Rack '+number+' '+state);row.append(cell)}
    function renderLedger(){if(!currentScorecard||!currentComparison)return;const own=currentComparison.own_racks||[];const opponent=currentComparison.opponent_racks||[];const locked=['finalized','corrected'].includes(currentScorecard.status);const played=Math.max(own.length,opponent.length);const columns=Math.max(1,played+(locked?0:1));const head=ledger.querySelector('thead');const body=ledger.querySelector('tbody');head.replaceChildren();body.replaceChildren();const headerRow=document.createElement('tr');const blank=document.createElement('th');blank.className='row-label rack-head';blank.scope='col';blank.textContent='Player';headerRow.append(blank);for(let number=1;number<=columns;number+=1){const state=rackState(own[number-1],opponent[number-1],number);const th=document.createElement('th');th.className='rack-head';th.dataset.state=state;th.scope='col';const n=document.createElement('span');n.className='rack-number';n.textContent='R'+number;const game=document.createElement('span');game.className='game-chip';game.textContent=gameForRack(number)==='9-ball'?'9':'8';game.setAttribute('aria-label',gameForRack(number));th.append(n,game);headerRow.append(th)}head.append(headerRow);const rows=[['A',currentScorecard.player_a_id,currentScorecard.player_a_display_name],['B',currentScorecard.player_b_id,currentScorecard.player_b_display_name]];for(const item of rows){const side=item[0],playerId=item[1],name=item[2];const row=document.createElement('tr');const label=document.createElement('th');label.className='row-label';label.scope='row';label.textContent=name;row.append(label);const history=rowHistoryForPlayer(playerId);const editable=currentComparison.tracker_player_id===playerId&&!locked&&!currentComparison.own_confirmed_at;for(let i=0;i<columns;i+=1){appendCell(row,history[i],side,rackState(own[i],opponent[i],i+1),i+1,name,editable)}body.append(row)}const statusRow=document.createElement('tr');const statusLabel=document.createElement('th');statusLabel.className='row-label';statusLabel.scope='row';statusLabel.textContent='Status';statusRow.append(statusLabel);const mismatches=[];let pending=0;for(let i=0;i<columns;i+=1){const state=rackState(own[i],opponent[i],i+1);appendStatusCell(statusRow,state,i+1);if(state==='mismatch')mismatches.push(i+1);if(state==='pending')pending+=1}body.append(statusRow);setText('[data-ledger-state]',mismatches.length?mismatches.length+' rack'+(mismatches.length===1?'':'s')+' need attention':pending?pending+' pending submission'+(pending===1?'':'s'):'Both sides aligned');requestAnimationFrame(()=>{if(ledgerRestoreLeft!=null){ledgerScroll.scrollLeft=ledgerRestoreLeft;ledgerRestoreLeft=null}else{ledgerScroll.scrollLeft=ledgerScroll.scrollWidth}})}
    function renderScorecard(scorecard){currentScorecard=scorecard;setText('[data-player-a-name]',scorecard.player_a_display_name);setText('[data-player-b-name]',scorecard.player_b_display_name);setText('[data-player-a-rating]',ratingText(scorecard.player_a_fargo_rating,scorecard.player_a_rating_status));setText('[data-player-b-rating]',ratingText(scorecard.player_b_fargo_rating,scorecard.player_b_rating_status));setText('[data-target-a]',scorecard.race_to_a);setText('[data-target-b]',scorecard.race_to_b);setText('[data-race-status]',scorecard.status);setText('[data-detail-break]',sideName(scorecard.first_break));setText('[data-detail-status]',scorecard.status);setText('[data-detail-team]',scoringTeamName);renderOpeningChoice(scorecard.opening_discipline||'8-ball',false)}
    function renderContext(context){currentContext=context||null;if(!context){setText('[data-match-context]','Current player match');return}setText('[data-match-context]','Round '+context.round_number+' • Match '+context.match_number+' of '+context.match_count);setText('[data-team-a-name]',context.team_a_name);setText('[data-team-b-name]',context.team_b_name);setText('[data-team-score-a]',context.team_score_a);setText('[data-team-score-b]',context.team_score_b)}
    function renderComparison(comparison){currentComparison=comparison;const locked=currentScorecard&&['finalized','corrected'].includes(currentScorecard.status);const own=comparison.own_racks||[];const opponent=comparison.opponent_racks||[];const started=own.length>0||opponent.length>0;renderOpeningChoice(currentScorecard?.opening_discipline||'8-ball',locked||started);const score=reconciledScore(comparison);setText('[data-score-a]',score[0]);setText('[data-score-b]',score[1]);renderLedger();const nextRack=own.length+1;setText('[data-next-rack]',nextRack);setText('[data-next-discipline]',gameForRack(nextRack));addRackButton.textContent='Add Rack '+nextRack+' · '+gameForRack(nextRack);rackAButton.textContent=currentScorecard.player_a_display_name+' wins';rackBButton.textContent=currentScorecard.player_b_display_name+' wins';if(comparison.histories_match){reconcileEl.dataset.state='match';setText('[data-reconcile-title]',comparison.both_confirmed?'Scores match · both confirmed':'Scores match');setText('[data-reconcile-detail]',comparison.ready_to_finalize?'Ready to finalize':'Waiting for both confirmations')}else{reconcileEl.dataset.state='mismatch';setText('[data-reconcile-title]',comparison.mismatch_rack_number?'Mismatch at rack '+comparison.mismatch_rack_number:'Waiting for the other team');setText('[data-reconcile-detail]',comparison.mismatch_rack_number?'Compare the W/L column above':'Both teams keep their own score')}addRackButton.disabled=locked||Boolean(comparison.own_confirmed_at);rackAButton.disabled=addRackButton.disabled;rackBButton.disabled=addRackButton.disabled;undoButton.disabled=locked||Boolean(comparison.own_confirmed_at)||!own.length;confirmButton.disabled=locked||Boolean(comparison.own_confirmed_at)||!own.length;finalizeButton.disabled=locked||!comparison.ready_to_finalize;if(editingRackNumber&&!own[editingRackNumber-1]&&!(opponent[editingRackNumber-1]&&editingRackNumber===own.length+1))closeRackEditor()}
    function renderPerspective(){const perspectives=adapter.perspectives||[];if(!perspectives.length){perspectiveEl.dataset.open='false';return}perspectiveEl.dataset.open='true';const current=adapter.perspective();for(const button of perspectiveButtons){const info=perspectives.find(item=>item.side===button.dataset.perspectiveSide);if(info)button.textContent=info.name;button.setAttribute('aria-pressed',String(button.dataset.perspectiveSide===current))}}
    async function loadAll({quiet=false}={}){if(!quiet)setStatus(adapter.mode==='sandbox'?'Loading practice…':'Loading…');const result=await adapter.load();renderScorecard(result.scorecard);renderContext(result.context);renderComparison(result.comparison);scoringTeamId=adapter.scoringTeamId();scoringTeamName=adapter.scoringTeamName();setText('[data-detail-team]',scoringTeamName);renderPerspective();const signature=JSON.stringify(result.comparison.own_racks||[]);if(quiet&&lastOwnSignature!=null&&signature!==lastOwnSignature)setStatus('Score updated on another device','ok');else if(!quiet)setStatus(adapter.mode==='sandbox'?'Practice · production scorer':'Live','ok');lastOwnSignature=signature}
    async function chooseOpeningDiscipline(openingDiscipline){setStatus('Saving game order…');await adapter.setOpeningDiscipline({openingDiscipline,scoringTeamId});await loadAll();setStatus((openingDiscipline==='9-ball'?'9-ball':'8-ball')+' will be played first.','ok')}
    async function recordRack(winner){setStatus('Saving rack…');const nextRack=(currentComparison?.own_racks||[]).length+1;await adapter.saveRack({winnerSide:winner,scoringTeamId,discipline:gameForRack(nextRack)});winnerPicker.dataset.open='false';await loadAll()}
    async function updateRack(rackNumber,result){const side=trackerSide();const winner=result==='W'?side:oppositeSide(side);const own=currentComparison?.own_racks||[];const existing=Boolean(own[rackNumber-1]);ledgerRestoreLeft=ledgerScroll.scrollLeft;setStatus((existing?'Updating':'Answering')+' rack '+rackNumber+'…');const body=existing?{rackNumber,winnerSide:winner,scoringTeamId}:{winnerSide:winner,scoringTeamId};body.discipline=gameForRack(rackNumber);await adapter.saveRack(body);closeRackEditor();await loadAll();setStatus('Rack '+rackNumber+' updated','ok')}
    async function undoRack(){setStatus('Undoing rack…');await adapter.undo({scoringTeamId});await loadAll()}
    async function confirmScore(){setStatus('Confirming score…');await adapter.confirm({scoringTeamId});await loadAll()}
    async function finalizeMatch(){setStatus('Finalizing match…');await adapter.finalize({scoringTeamId});await loadAll();setStatus(adapter.mode==='sandbox'?'Practice finalized':'Finalized','ok')}
    function openRackEditor(number){if(!currentComparison||!currentScorecard)return;const own=currentComparison.own_racks||[];const opponent=currentComparison.opponent_racks||[];const ownRack=own[number-1];const opponentRack=opponent[number-1];const answeringPending=!ownRack&&Boolean(opponentRack)&&number===own.length+1;if((!ownRack&&!answeringPending)||currentComparison.own_confirmed_at||['finalized','corrected'].includes(currentScorecard.status))return;editingRackNumber=number;const side=trackerSide();const otherSide=oppositeSide(side);setText('[data-edit-rack-number]',number);setText('[data-edit-discipline]',gameForRack(number));setText('[data-edit-own-label]',sideName(side)+' · your team');setText('[data-edit-own-value]',answeringPending?'—':cellValue(ownRack,side));setText('[data-edit-opponent-label]',sideName(otherSide)+' · other team');setText('[data-edit-opponent-value]',cellValue(opponentRack,otherSide));for(const button of editResultButtons)button.setAttribute('aria-pressed',String(!answeringPending&&button.dataset.editResult===cellValue(ownRack,side)));editPanel.hidden=false;editPanel.scrollIntoView({block:'nearest',behavior:'smooth'})}
    function closeRackEditor(){editingRackNumber=null;editPanel.hidden=true}
    async function run(action){try{await action()}catch(error){if(error.message.includes('Score changed on another device')){winnerPicker.dataset.open='false';closeRackEditor();await loadAll({quiet:true});setStatus('Score changed on another phone','error');showError('Score changed on another phone. We refreshed it—check the current rack before scoring.');return}setStatus('Action failed','error');showError(error.message)}}
    function startRefresh(){clearInterval(refreshTimer);if(adapter.liveRefresh===false)return;refreshTimer=setInterval(()=>{if(document.visibilityState==='visible'&&!editingRackNumber)run(()=>loadAll({quiet:true}))},3000)}
    for(const button of openingButtons)button.addEventListener('click',()=>run(()=>chooseOpeningDiscipline(button.dataset.opening)));
    addRackButton.addEventListener('click',()=>{winnerPicker.dataset.open=winnerPicker.dataset.open==='true'?'false':'true'});
    rackAButton.addEventListener('click',()=>run(()=>recordRack('A')));rackBButton.addEventListener('click',()=>run(()=>recordRack('B')));
    ledger.addEventListener('click',(event)=>{const button=event.target.closest('[data-edit-rack]');if(button)openRackEditor(Number(button.dataset.editRack))});
    editClose.addEventListener('click',closeRackEditor);for(const button of editResultButtons)button.addEventListener('click',()=>{if(editingRackNumber)run(()=>updateRack(editingRackNumber,button.dataset.editResult))});
    document.querySelector('[data-edit-current]').addEventListener('click',()=>{const own=currentComparison?.own_racks||[];if(own.length)openRackEditor(own.length)});
    undoButton.addEventListener('click',()=>run(undoRack));confirmButton.addEventListener('click',()=>run(confirmScore));finalizeButton.addEventListener('click',()=>run(finalizeMatch));
    for(const button of perspectiveButtons)button.addEventListener('click',()=>run(async()=>{if(!adapter.setPerspective)return;await adapter.setPerspective(button.dataset.perspectiveSide);scoringTeamId=adapter.scoringTeamId();scoringTeamName=adapter.scoringTeamName();closeRackEditor();winnerPicker.dataset.open='false';lastOwnSignature=null;await loadAll()}));
    const switchLink=document.querySelector('[data-switch-match]');switchLink.href=adapter.switchHref||'/scorecard';switchLink.textContent=adapter.switchLabel||'Switch match';
    if(adapter.mode==='sandbox'){document.querySelector('[data-sandbox-banner]').hidden=false;document.querySelector('[data-sandbox-footer]').hidden=false;const feedback=document.querySelector('[data-sandbox-feedback]');try{feedback.value=localStorage.getItem('fd.sandboxFeedback.player.v1')||''}catch{}document.querySelector('[data-save-feedback]').addEventListener('click',()=>{try{localStorage.setItem('fd.sandboxFeedback.player.v1',feedback.value);setStatus('Practice feedback saved on this device','ok')}catch{setStatus('Could not save feedback','error')}})}
    run(loadAll);startRefresh();
  })();
`;
