export function renderSchedulePage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Fremont Derby Schedule</title>
  <style>
    :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#101214;color:#f5f0e8;--panel:#191d22;--line:#343c45;--muted:#aab3bb;--green:#2fa972;--gold:#e9bd45}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:#101214}button,select{font:inherit}.app{width:min(980px,100%);margin:auto;padding:16px}.topbar{display:flex;justify-content:space-between;gap:12px;align-items:center;padding-bottom:14px;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:10px;font-weight:950}.mark{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(#f4d64b 0 34%,#fff 34% 66%,#f4d64b 66%);color:#111;font-weight:950}.status{min-height:28px;color:var(--muted);text-align:right}.status[data-tone="error"]{color:#ffb1aa}.status[data-tone="ok"]{color:#9ee5bd}.controls{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:14px 0}label{display:grid;gap:6px;color:var(--muted);font-size:.78rem;font-weight:900}select{width:100%;min-height:48px;padding:0 12px;border:1px solid var(--line);border-radius:10px;background:#0d1013;color:#fff}.round{border:1px solid var(--line);border-radius:13px;background:var(--panel);overflow:hidden}.round-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px;border-bottom:1px solid var(--line)}.kicker{color:#9ee5bd;font-size:.72rem;font-weight:950;letter-spacing:.08em;text-transform:uppercase}.round-head h1{margin:3px 0 0;font-size:clamp(1.5rem,5vw,2.2rem)}.round-meta{color:var(--muted);font-size:.85rem;text-align:right}.matches{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:12px}.match{min-width:0;display:grid;gap:10px;padding:13px;border:1px solid var(--line);border-top:4px solid var(--gold);border-radius:11px;background:#12171b}.match-top{display:flex;justify-content:space-between;gap:10px;color:var(--muted);font-size:.75rem;font-weight:850}.versus{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:8px;align-items:center}.versus strong{overflow-wrap:anywhere;font-size:1rem}.versus strong:last-child{text-align:right}.versus span{color:var(--gold);font-size:.72rem;font-weight:950;text-transform:uppercase}.match-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.match-actions a{min-height:44px;display:grid;place-items:center;padding:8px;border:1px solid var(--line);border-radius:9px;color:#f5f0e8;text-decoration:none;font-size:.8rem;font-weight:900}.match-actions a.primary{border-color:var(--green);background:var(--green);color:#06120d}.empty{padding:24px;color:var(--muted);text-align:center}.empty a{color:#f0d48b}.round[hidden],.empty[hidden]{display:none}
    @media(max-width:700px){.app{padding:12px}.topbar{align-items:flex-start}.status{text-align:left}.controls,.matches{grid-template-columns:1fr}.round-head{align-items:flex-start}.round-meta{text-align:left}.match{min-height:152px}}
  </style>
</head>
<body>
  <main class="app">
    <header class="topbar"><div class="brand"><span class="mark">9</span><span>Fremont Derby Schedule</span></div><div class="status" data-status>Loading…</div></header>
    <section class="controls" aria-label="Schedule selection">
      <label>Season<select data-season-select><option value="">Loading seasons…</option></select></label>
      <label>League night<select data-round-select disabled><option value="">Choose a season</option></select></label>
    </section>
    <section class="round" data-round-panel hidden>
      <div class="round-head">
        <div><span class="kicker" data-round-kicker>Next league night</span><h1 data-round-title>Round</h1></div>
        <div class="round-meta"><strong data-round-date>Date</strong><br /><span data-round-status>Status</span></div>
      </div>
      <div class="matches" data-match-list></div>
    </section>
    <div class="empty" data-empty hidden>No schedule has been published for this season yet. <a href="/teams">Open Teams</a></div>
  </main>
  <script>
    const seasonSelect=document.querySelector('[data-season-select]');const roundSelect=document.querySelector('[data-round-select]');const statusEl=document.querySelector('[data-status]');const panel=document.querySelector('[data-round-panel]');const roundKicker=document.querySelector('[data-round-kicker]');const roundTitle=document.querySelector('[data-round-title]');const roundDate=document.querySelector('[data-round-date]');const roundStatus=document.querySelector('[data-round-status]');const matchList=document.querySelector('[data-match-list]');const emptyEl=document.querySelector('[data-empty]');const query=new URLSearchParams(location.search);const requestedSeason=query.get('season')||localStorage.getItem('fd.scheduleSeasonId')||'';const requestedRound=query.get('round')||localStorage.getItem('fd.scheduleRoundId')||'';let seasons=[];let rounds=[];
    function setStatus(message,tone){statusEl.textContent=message;statusEl.dataset.tone=tone||'muted'}async function json(response){const text=await response.text();if(!text)return{};try{return JSON.parse(text)}catch{return{error:text}}}async function get(path){const response=await fetch(path);const body=await json(response);if(!response.ok)throw new Error(body.error||'We could not load the schedule.');return body}function dateLabel(value){if(!value)return'Date TBD';const date=new Date(value+'T12:00:00');return new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(date)}function stageLabel(round){if(round.stage==='championship')return'Championship';if(round.stage==='semifinal')return'Semifinals';if(round.stage==='tiebreaker')return'Tiebreaker';return'Round '+round.roundNumber}function statusLabel(value){return String(value||'scheduled').replaceAll('_',' ')}function stageRank(round){if(round.stage==='championship')return 4;if(round.stage==='semifinal')return 3;if(round.stage==='tiebreaker')return 2;return 1}function dateDistance(value){const parsed=Date.parse(value||'');return Number.isFinite(parsed)?Math.abs(parsed-Date.now()):0}function preferredRound(){if(requestedRound&&rounds.some((round)=>round.roundId===requestedRound))return requestedRound;const today=new Date().toISOString().slice(0,10);const seasonMeta=seasons.find((s)=>s.id===seasonSelect.value);const seasonComplete=seasonMeta&&String(seasonMeta.status||'')==='complete';const live=rounds.filter((round)=>round.matches.some((match)=>match.status==='in_progress'));if(live.length&&!seasonComplete)return live.sort((left,right)=>stageRank(right)-stageRank(left)||dateDistance(left.scheduledOn)-dateDistance(right.scheduledOn))[0].roundId;if(seasonComplete){const finalized=rounds.filter((round)=>round.matches.some((match)=>match.status==='finalized')||round.status==='finalized');if(finalized.length)return finalized.sort((left,right)=>stageRank(right)-stageRank(left))[0].roundId}const upcoming=rounds.find((round)=>!round.scheduledOn||round.scheduledOn>=today);return(upcoming||rounds[rounds.length-1]||{}).roundId||''}
    function renderSeasons(){seasonSelect.replaceChildren();if(!seasons.length){const option=document.createElement('option');option.value='';option.textContent='No public seasons';seasonSelect.append(option);seasonSelect.disabled=true;roundSelect.disabled=true;emptyEl.hidden=false;panel.hidden=true;return}for(const season of seasons){const option=document.createElement('option');option.value=season.id;option.textContent=season.name+' · '+statusLabel(season.status);seasonSelect.append(option)}const current=seasons.find((season)=>['active','playoffs'].includes(season.status))||seasons[0];seasonSelect.value=requestedSeason&&seasons.some((season)=>season.id===requestedSeason)?requestedSeason:current.id;seasonSelect.disabled=false}
    function renderRoundOptions(){roundSelect.replaceChildren();if(!rounds.length){const option=document.createElement('option');option.value='';option.textContent='Schedule not published';roundSelect.append(option);roundSelect.disabled=true;panel.hidden=true;emptyEl.hidden=false;return}for(const round of rounds){const option=document.createElement('option');option.value=round.roundId;option.textContent=stageLabel(round)+' · '+dateLabel(round.scheduledOn);roundSelect.append(option)}roundSelect.value=preferredRound();roundSelect.disabled=false;emptyEl.hidden=true;renderRound()}
    function renderRound(){const round=rounds.find((item)=>item.roundId===roundSelect.value);if(!round){panel.hidden=true;return}const today=new Date().toISOString().slice(0,10);roundKicker.textContent=round.scheduledOn===today?'Tonight':(round.scheduledOn&&round.scheduledOn>today?'Next league night':'League night');roundTitle.textContent=stageLabel(round);roundDate.textContent=dateLabel(round.scheduledOn);roundStatus.textContent=statusLabel(round.status);matchList.replaceChildren();for(const match of round.matches){const card=document.createElement('article');card.className='match';const top=document.createElement('div');top.className='match-top';const table=document.createElement('span');table.textContent='Table '+match.tableNumber;const state=document.createElement('span');state.textContent=statusLabel(match.status);top.append(table,state);const versus=document.createElement('div');versus.className='versus';const teamA=document.createElement('strong');teamA.textContent=match.teamAName;const vs=document.createElement('span');vs.textContent='vs';const teamB=document.createElement('strong');teamB.textContent=match.teamBName;versus.append(teamA,vs,teamB);const actions=document.createElement('div');actions.className='match-actions';const score=document.createElement('a');const finalized=match.status==='finalized'||match.status==='corrected';score.className=finalized?'':'primary';score.href='/scorecard?match='+encodeURIComponent(match.teamMatchId||'');score.textContent=finalized?'View':'Score';const messages=document.createElement('a');messages.href='/messages?matchup='+encodeURIComponent(match.teamMatchId);messages.textContent='Messages';actions.append(score,messages);card.append(top,versus,actions);matchList.append(card)}if(!round.matches.length){const noMatches=document.createElement('div');noMatches.className='empty';noMatches.textContent='No matchups are posted for this league night.';matchList.append(noMatches)}panel.hidden=false;localStorage.setItem('fd.scheduleRoundId',round.roundId);const url=new URL(location.href);url.searchParams.set('season',seasonSelect.value);url.searchParams.set('round',round.roundId);history.replaceState({},'',url)}
    async function loadSchedule(){const seasonId=seasonSelect.value;if(!seasonId)return;setStatus('Loading schedule…');const body=await get('/api/seasons/'+encodeURIComponent(seasonId)+'/schedule');rounds=body.rounds||[];localStorage.setItem('fd.scheduleSeasonId',seasonId);renderRoundOptions();setStatus(rounds.length?'Schedule ready':'Schedule not published',rounds.length?'ok':'muted')}
    async function bootstrap(){const body=await get('/api/seasons');seasons=body.seasons||[];renderSeasons();if(seasonSelect.value)await loadSchedule()}async function run(action){try{await action()}catch(error){setStatus(error.message,'error');panel.hidden=true;emptyEl.hidden=false}}seasonSelect.addEventListener('change',()=>run(loadSchedule));roundSelect.addEventListener('change',renderRound);run(bootstrap);
  </script>
</body>
</html>`;
}
