export function renderScorecardPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Fremont Derby Scorecard</title>
  <style>
    :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#0c1210;color:#f6f1e7;--panel:#152019;--panel2:#101813;--line:#32473a;--muted:#a8b7ae;--green:#43bd7d;--gold:#e6bd46;--red:#e36c61;--blue:#69a2ef;--ink:#07110b}
    *{box-sizing:border-box}
    body{margin:0;min-height:100vh;overflow-x:hidden;background:radial-gradient(circle at 50% 0,#173323,#0c1210 28rem)}
    button{font:inherit;min-height:48px;border:1px solid transparent;border-radius:11px;padding:9px 12px;font-weight:950;cursor:pointer;touch-action:manipulation}
    button:disabled{opacity:.42;cursor:not-allowed}
    button:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #bcebd0;outline-offset:2px}
    .app{width:min(760px,100%);margin:auto;padding:8px}
    .topbar{min-height:40px;display:flex;align-items:center;justify-content:space-between;gap:9px}
    .brand{display:flex;align-items:center;gap:7px;font-weight:950}.balls{display:flex;gap:3px}.ball{width:23px;height:23px;border-radius:50%;display:grid;place-items:center;background:#f7f4eb;color:#111;font-size:.7rem;font-weight:1000}.ball.nine{background:linear-gradient(#e2b737 0 34%,#f7f4eb 34% 66%,#e2b737 66%)}
    .status{font-size:.76rem;color:var(--muted);text-align:right}.status[data-tone=error]{color:#ffb5ae}.status[data-tone=ok]{color:#a7ebc1}
    .match-context{min-height:42px;display:flex;align-items:center;justify-content:space-between;gap:8px;border-top:1px solid var(--line);color:var(--muted);font-size:.77rem}.match-context strong{color:#f6df9d}.match-context a{color:#c7ead5;font-weight:900;text-decoration:none;white-space:nowrap}
    .team-score{border:1px solid var(--line);border-radius:15px;background:linear-gradient(120deg,#172a1f,#122019);padding:10px 12px;display:grid;gap:7px}.team-score-label{text-align:center;color:var(--gold);font-size:.68rem;font-weight:950;letter-spacing:.11em;text-transform:uppercase}.team-score-grid{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:10px}.team-block{min-width:0;display:grid;gap:2px}.team-block:last-child{text-align:right}.team-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#dce8e1;font-size:.78rem;font-weight:850}.team-points{font-size:clamp(2.1rem,11vw,3.5rem);line-height:.85;font-weight:1000;letter-spacing:-.07em}.team-separator{color:var(--muted);font-weight:950}
    .opening-setup{margin-top:8px;padding:8px;border:1px solid var(--line);border-radius:13px;background:var(--panel2);display:grid;grid-template-columns:minmax(0,1fr) minmax(180px,.65fr);gap:8px;align-items:center}.opening-copy strong{display:block;font-size:.82rem}.opening-copy span{display:block;margin-top:2px;color:var(--muted);font-size:.66rem}.opening-options{display:grid;grid-template-columns:1fr 1fr;gap:6px}.opening-option{min-height:44px;background:#202a24;color:#f6f1e7;border-color:var(--line)}.opening-option[aria-pressed=true]{background:var(--gold);border-color:var(--gold);color:#171103}.opening-setup[data-locked=true] .opening-copy span{color:#a7ebc1}
    .race{margin-top:8px;border:1px solid var(--line);border-radius:15px;background:var(--panel);overflow:hidden}.race-context{padding:8px 10px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:8px;color:var(--muted);font-size:.68rem}.race-context strong{color:#fff}.players{display:grid;grid-template-columns:1fr 1fr}.player{min-width:0;padding:10px}.player+.player{border-left:1px solid var(--line);text-align:right}.player-name{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:clamp(1rem,4.5vw,1.35rem)}.player-meta{margin-top:2px;color:var(--muted);font-size:.66rem}.race-score{display:flex;align-items:baseline;gap:7px;margin-top:5px}.player+.player .race-score{justify-content:flex-end}.race-score strong{font-size:clamp(2.7rem,14vw,4.4rem);line-height:.8;letter-spacing:-.08em}.race-score span{color:var(--muted);font-size:.72rem;font-weight:850}.race-score span b{color:var(--gold);font-size:1rem}
    .ledger-panel{margin-top:8px;border:1px solid var(--line);border-radius:15px;background:var(--panel);overflow:hidden}.ledger-head{min-height:46px;padding:8px 10px;display:flex;align-items:center;justify-content:space-between;gap:8px;border-bottom:1px solid var(--line)}.ledger-head strong{font-size:.88rem}.ledger-state{color:var(--muted);font-size:.69rem;text-align:right}.ledger-scroll{max-width:100%;overflow-x:auto;overscroll-behavior-x:contain;scrollbar-width:thin}.ledger{border-collapse:separate;border-spacing:0;min-width:100%;width:max-content}.ledger th,.ledger td{min-width:58px;height:48px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);text-align:center;padding:4px}.ledger tr:last-child th,.ledger tr:last-child td{border-bottom:0}.ledger th:last-child,.ledger td:last-child{border-right:0}.ledger .row-label{position:sticky;left:0;z-index:2;width:112px;min-width:112px;max-width:112px;padding:5px 7px;background:#111b15;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.72rem}.rack-head{background:#111914}.rack-head[data-state=mismatch]{background:#351918}.rack-head[data-state=pending]{background:#2e2917}.rack-number{display:block;font-size:.7rem}.game-chip{display:inline-flex;align-items:center;justify-content:center;min-width:24px;min-height:20px;margin-top:2px;border:1px solid #5a685f;border-radius:999px;color:#dfe9e3;font-size:.62rem;font-weight:950}.submission{font-size:1.05rem;font-weight:1000;background:#101713}.submission[data-value=W]{color:#a7ebc1}.submission[data-value=L]{color:#ffb4ae}.submission[data-state=matched]{box-shadow:inset 0 -3px 0 var(--green)}.submission[data-state=pending]{box-shadow:inset 0 -3px 0 var(--gold);background:#2e2917}.submission[data-state=mismatch]{box-shadow:inset 0 -3px 0 var(--red);background:#351918}.submission[data-state=unplayed]{color:#68756e}.rack-edit{width:100%;height:100%;min-height:40px;padding:3px;background:transparent;color:inherit;border-color:transparent;border-radius:8px;font-size:1.05rem}.rack-edit::after{content:'✎';display:block;margin-top:1px;color:#a8b7ae;font-size:.48rem}.rack-edit[data-pending=true]::after{content:'answer';font-size:.45rem}.rack-status{font-size:.78rem;font-weight:1000}.rack-status[data-state=matched]{color:#8ce0ad}.rack-status[data-state=pending]{color:#f0cb67;background:#2e2917}.rack-status[data-state=mismatch]{color:#ff8c83;background:#351918}.rack-status[data-state=unplayed]{color:#68756e}
    .edit-panel{margin-top:8px;padding:10px;border:1px solid #5e7568;border-radius:14px;background:#142019}.edit-panel[hidden]{display:none}.edit-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.edit-head strong{font-size:.9rem}.edit-head span{display:block;margin-top:2px;color:var(--muted);font-size:.67rem}.edit-close{min-width:44px;min-height:44px;padding:4px;background:transparent;color:#f6f1e7;border-color:var(--line)}.edit-compare{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.edit-value{padding:7px;border:1px solid var(--line);border-radius:9px;background:#101713}.edit-value span{display:block;color:var(--muted);font-size:.61rem}.edit-value strong{display:block;margin-top:2px;font-size:1rem}.edit-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.edit-result{min-height:54px;background:#244e35;color:#fff;border-color:#4c8f68}.edit-result[data-result=L]{background:#4b2825;border-color:#8b4d47}.edit-note{margin:7px 1px 0;color:var(--muted);font-size:.64rem;line-height:1.35}
    .next-rack{margin-top:8px}.add-rack{width:100%;min-height:58px;background:#0f6a40;color:#fff;border-color:#4cc98a;font-size:.98rem}.winner-picker{display:none;grid-template-columns:1fr 1fr;gap:7px;margin-top:7px;padding:8px;border:1px solid var(--line);border-radius:12px;background:#101813}.winner-picker[data-open=true]{display:grid}.winner{min-height:56px;background:var(--green);color:var(--ink);overflow:hidden;text-overflow:ellipsis}.winner[data-side=B]{background:var(--blue);color:#07101f}
    .reconcile{margin-top:8px;padding:9px 10px;border:1px solid var(--line);border-radius:12px;background:#111713;display:flex;justify-content:space-between;align-items:center;gap:8px}.reconcile[data-state=match]{border-color:#367d55}.reconcile[data-state=mismatch]{border-color:#9c4d45;background:#241817}.reconcile strong{font-size:.8rem}.reconcile span{color:var(--muted);font-size:.67rem;text-align:right}.actions{display:grid;grid-template-columns:.72fr 1fr 1fr;gap:6px;padding:8px 0}.undo{background:transparent;color:#f6f1e7;border-color:var(--line)}.confirm{background:var(--gold);color:#161003}.finalize{background:var(--red);color:#1a0604}
    .details{border:1px solid var(--line);border-radius:11px;background:#111713;overflow:hidden}.details summary{min-height:44px;padding:11px;cursor:pointer;color:#f6df9d;font-size:.78rem;font-weight:900}.detail-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;padding:9px;border-top:1px solid var(--line)}.detail{min-width:0}.detail span{display:block;color:var(--muted);font-size:.6rem}.detail strong{display:block;margin-top:2px;overflow-wrap:anywhere;font-size:.72rem}
    .error-popup{position:fixed;z-index:30;left:50%;bottom:16px;width:min(430px,calc(100% - 24px));transform:translateX(-50%);display:none;padding:11px 13px;border:1px solid #d9665d;border-radius:12px;background:#351918;box-shadow:0 12px 30px #0008;color:#fff}.error-popup[data-open=true]{display:block}.error-popup strong{display:block;font-size:.8rem}.error-popup span{display:block;margin-top:2px;color:#ffd1cd;font-size:.7rem}
    @media(max-width:520px){.app{padding:6px}.brand>span:last-child{font-size:.8rem}.match-context{align-items:flex-start;padding:5px 0}.opening-setup{grid-template-columns:1fr}.team-score{padding:9px}.row-label{width:96px!important;min-width:96px!important;max-width:96px!important}.ledger th,.ledger td{min-width:54px}.winner{padding:7px;font-size:.8rem}.actions button{min-height:48px;padding:6px 4px;font-size:.71rem}.detail-grid{grid-template-columns:1fr 1fr}}
  </style>
</head>
<body>
  <main class="app">
    <header class="topbar"><div class="brand"><span class="balls" aria-hidden="true"><span class="ball">8</span><span class="ball nine">9</span></span><span>Fremont Derby</span></div><div class="status" data-status>Loading…</div></header>
    <div class="match-context"><span data-match-context>Loading round and match…</span><a href="/scorecard">Switch match</a></div>

    <section class="team-score" aria-label="Running team score">
      <div class="team-score-label">Running team score</div>
      <div class="team-score-grid"><div class="team-block"><span class="team-name" data-team-a-name>Team A</span><strong class="team-points" data-team-score-a>0</strong></div><span class="team-separator">–</span><div class="team-block"><span class="team-name" data-team-b-name>Team B</span><strong class="team-points" data-team-score-b>0</strong></div></div>
    </section>

    <section class="opening-setup" data-opening-setup aria-label="Opening game order"><div class="opening-copy"><strong>Which game first?</strong><span data-opening-note>Choose before rack 1. Racks 1–3 use this game.</span></div><div class="opening-options"><button class="opening-option" data-opening="8-ball" type="button" aria-pressed="false">8 first</button><button class="opening-option" data-opening="9-ball" type="button" aria-pressed="false">9 first</button></div></section>

    <section class="race" aria-label="Current individual race">
      <div class="race-context"><span>Current individual race</span><strong data-race-status>Scheduled</strong></div>
      <div class="players"><article class="player"><h2 class="player-name" data-player-a-name>Player A</h2><div class="player-meta" data-player-a-rating>Rating</div><div class="race-score"><strong data-score-a>0</strong><span>race to <b data-target-a>–</b></span></div></article><article class="player"><h2 class="player-name" data-player-b-name>Player B</h2><div class="player-meta" data-player-b-rating>Rating</div><div class="race-score"><strong data-score-b>0</strong><span>race to <b data-target-b>–</b></span></div></article></div>
    </section>

    <section class="ledger-panel" aria-label="Rack-by-rack score ledger"><header class="ledger-head"><strong>Rack ledger</strong><span class="ledger-state" data-ledger-state>Loading both submissions…</span></header><div class="ledger-scroll" data-ledger-scroll><table class="ledger" data-ledger><thead></thead><tbody></tbody></table></div></section>

    <section class="edit-panel" data-edit-panel hidden aria-live="polite">
      <div class="edit-head"><div><strong>Edit Rack <span data-edit-rack-number>–</span> · <span data-edit-discipline>–</span></strong><span>Change only your team’s submission.</span></div><button class="edit-close" data-edit-close type="button" aria-label="Close rack editor">×</button></div>
      <div class="edit-compare"><div class="edit-value"><span data-edit-own-label>Your submission</span><strong data-edit-own-value>–</strong></div><div class="edit-value"><span data-edit-opponent-label>Other team</span><strong data-edit-opponent-value>–</strong></div></div>
      <div class="edit-actions"><button class="edit-result" data-edit-result="W" type="button">W · Win</button><button class="edit-result" data-result="L" data-edit-result="L" type="button">L · Loss</button></div>
      <p class="edit-note">Later racks stay exactly as entered. Changing this rack clears your team’s confirmation so the corrected score can be confirmed again.</p>
    </section>

    <section class="next-rack" aria-label="Record next rack"><button class="add-rack" data-add-rack type="button">Add Rack 1</button><div class="winner-picker" data-winner-picker><button class="winner" data-rack-a data-side="A" type="button">Player A wins</button><button class="winner" data-rack-b data-side="B" type="button">Player B wins</button></div><span hidden data-next-rack>1</span><span hidden data-next-discipline>8-ball</span></section>

    <section class="reconcile" data-reconcile aria-live="polite"><strong data-reconcile-title>Loading both score records…</strong><span data-reconcile-detail></span></section>
    <section class="actions" aria-label="Score controls"><button class="undo" data-undo type="button">Undo last</button><button class="confirm" data-confirm type="button">Confirm ours</button><button class="finalize" data-finalize type="button">Finalize match</button></section>
    <details class="details"><summary>Match details</summary><div class="detail-grid"><div class="detail"><span>Opening order</span><strong data-detail-opening>–</strong></div><div class="detail"><span>First break</span><strong data-detail-break>–</strong></div><div class="detail"><span>Match status</span><strong data-detail-status>–</strong></div><div class="detail"><span>Scoring for</span><strong data-detail-team>–</strong></div></div></details>
  </main>
  <div class="error-popup" data-error role="alert"><strong>Couldn’t complete that action</strong><span data-error-message></span></div>
  <script>
    const params=new URLSearchParams(location.search);const matchId=params.get('match')||'';const scoringTeamId=params.get('team')||'';const scoringTeamName=params.get('teamName')||'your team';
    const statusEl=document.querySelector('[data-status]');const rackAButton=document.querySelector('[data-rack-a]');const rackBButton=document.querySelector('[data-rack-b]');const addRackButton=document.querySelector('[data-add-rack]');const winnerPicker=document.querySelector('[data-winner-picker]');const undoButton=document.querySelector('[data-undo]');const confirmButton=document.querySelector('[data-confirm]');const finalizeButton=document.querySelector('[data-finalize]');const openingSetup=document.querySelector('[data-opening-setup]');const openingButtons=[...document.querySelectorAll('[data-opening]')];const openingNote=document.querySelector('[data-opening-note]');const ledger=document.querySelector('[data-ledger]');const ledgerScroll=document.querySelector('[data-ledger-scroll]');const reconcileEl=document.querySelector('[data-reconcile]');const editPanel=document.querySelector('[data-edit-panel]');const editClose=document.querySelector('[data-edit-close]');const editResultButtons=[...document.querySelectorAll('[data-edit-result]')];const errorPopup=document.querySelector('[data-error]');
    let currentScorecard=null;let currentComparison=null;let currentContext=null;let refreshTimer=null;let editingRackNumber=null;let ledgerRestoreLeft=null;
    function accessToken(){return sessionStorage.getItem('fd.accessToken')||''}
    function setStatus(message,tone){statusEl.textContent=message;statusEl.dataset.tone=tone||''}
    function setText(selector,value){document.querySelector(selector).textContent=value==null||value===''?'–':String(value)}
    function showError(message){document.querySelector('[data-error-message]').textContent=message;errorPopup.dataset.open='true';clearTimeout(showError.timer);showError.timer=setTimeout(()=>{errorPopup.dataset.open='false'},6500)}
    function requireContext(){const token=accessToken();if(!matchId)throw new Error('Choose a match from the scorecard list.');if(!scoringTeamId)throw new Error('Choose which team you are scoring for.');if(!token)throw new Error('Sign in with Google to score this match.');return{matchId,scoringTeamId,token}}
    async function api(path,options={}){const inputs=requireContext();const base=path.replace(':id',encodeURIComponent(inputs.matchId));const separator=base.includes('?')?'&':'?';const contextualPath=base+separator+'scoringTeamId='+encodeURIComponent(inputs.scoringTeamId);const response=await fetch(contextualPath,{...options,headers:{authorization:'Bearer '+inputs.token,'content-type':'application/json',...(options.headers||{})}});const body=await response.json();if(response.status===401){sessionStorage.removeItem('fd.accessToken');throw new Error('Your sign-in expired. Open Profile and sign in again.')}if(!response.ok)throw new Error(body.error||'Request failed');return body}
    function ratingText(rating,status){return[rating||'Unrated',status||'unverified'].join(' · ')}
    function sideName(side){if(!currentScorecard)return side;return side==='A'?currentScorecard.player_a_display_name:currentScorecard.player_b_display_name}
    function oppositeSide(side){return side==='A'?'B':'A'}
    function oppositeGame(game){return game==='9-ball'?'8-ball':'9-ball'}
    function gameForRack(number){if(!currentScorecard)return'–';return Number(number)<=Number(currentScorecard.opening_block_length||3)?currentScorecard.opening_discipline:oppositeGame(currentScorecard.opening_discipline)}
    function winnerSide(rack){return rack&&(rack.winnerSide||rack.winner_side)||null}
    function rackGame(rack,number){return rack&&rack.discipline||gameForRack(number)}
    function renderOpeningChoice(selected,locked){openingSetup.dataset.locked=String(locked);for(const button of openingButtons){button.setAttribute('aria-pressed',String(button.dataset.opening===selected));button.disabled=locked}openingNote.textContent=locked?'Order locked after rack 1 · '+(selected==='9-ball'?'9-ball first':'8-ball first'):'Choose before rack 1. Racks 1–3 use this game.';setText('[data-detail-opening]',selected==='9-ball'?'9-ball first':'8-ball first')}
    function rackState(own,opponent,number){if(!own&&!opponent)return'unplayed';if(!own||!opponent)return'pending';return winnerSide(own)===winnerSide(opponent)&&rackGame(own,number)===rackGame(opponent,number)?'matched':'mismatch'}
    function reconciledScore(comparison){let a=0,b=0;const own=comparison.own_racks||[];const opponent=comparison.opponent_racks||[];const count=Math.max(own.length,opponent.length);for(let i=0;i<count;i+=1){if(rackState(own[i],opponent[i],i+1)!=='matched')continue;const side=winnerSide(own[i]);if(side==='A')a+=1;if(side==='B')b+=1}return[a,b]}
    function trackerSide(){return currentComparison?.tracker_player_id===currentScorecard?.player_a_id?'A':'B'}
    function rowHistoryForPlayer(playerId){const own=currentComparison?.own_racks||[];const opponent=currentComparison?.opponent_racks||[];return currentComparison?.tracker_player_id===playerId?own:opponent}
    function cellValue(rack,playerSide){if(!rack)return'—';return winnerSide(rack)===playerSide?'W':'L'}
    function appendCell(row,rack,playerSide,state,number,name,editable){const cell=document.createElement('td');cell.className='submission';const value=cellValue(rack,playerSide);cell.dataset.value=value;cell.dataset.state=state;cell.setAttribute('aria-label','Rack '+number+', '+gameForRack(number)+', '+name+': '+(value==='—'?'no submission':value==='W'?'win':'loss')+', '+state);const canAnswerPending=editable&&!rack&&state==='pending';if(editable&&(rack||canAnswerPending)){const button=document.createElement('button');button.className='rack-edit';button.type='button';button.textContent=rack?value:'+';button.dataset.editRack=String(number);button.dataset.pending=String(canAnswerPending);button.setAttribute('aria-label',rack?'Edit '+name+' rack '+number+', currently '+(value==='W'?'win':'loss'):'Score '+name+' rack '+number+', waiting for your team');cell.append(button)}else{cell.textContent=value}row.append(cell)}
    function appendStatusCell(row,state,number){const cell=document.createElement('td');cell.className='rack-status';cell.dataset.state=state;cell.textContent=state==='matched'?'✓':state==='mismatch'?'⚠':state==='pending'?'…':'—';cell.setAttribute('aria-label','Rack '+number+' '+state);row.append(cell)}
    function renderLedger(){if(!currentScorecard||!currentComparison)return;const own=currentComparison.own_racks||[];const opponent=currentComparison.opponent_racks||[];const locked=['finalized','corrected'].includes(currentScorecard.status);const played=Math.max(own.length,opponent.length);const columns=Math.max(1,played+(locked?0:1));const head=ledger.querySelector('thead');const body=ledger.querySelector('tbody');head.replaceChildren();body.replaceChildren();const headerRow=document.createElement('tr');const blank=document.createElement('th');blank.className='row-label rack-head';blank.scope='col';blank.textContent='Player';headerRow.append(blank);for(let number=1;number<=columns;number+=1){const state=rackState(own[number-1],opponent[number-1],number);const th=document.createElement('th');th.className='rack-head';th.dataset.state=state;th.scope='col';const n=document.createElement('span');n.className='rack-number';n.textContent='R'+number;const game=document.createElement('span');game.className='game-chip';game.textContent=gameForRack(number)==='9-ball'?'9':'8';game.setAttribute('aria-label',gameForRack(number));th.append(n,game);headerRow.append(th)}head.append(headerRow);const rows=[['A',currentScorecard.player_a_id,currentScorecard.player_a_display_name],['B',currentScorecard.player_b_id,currentScorecard.player_b_display_name]];for(const item of rows){const side=item[0],playerId=item[1],name=item[2];const row=document.createElement('tr');const label=document.createElement('th');label.className='row-label';label.scope='row';label.textContent=name;row.append(label);const history=rowHistoryForPlayer(playerId);const editable=currentComparison.tracker_player_id===playerId&&!locked&&!currentComparison.own_confirmed_at;for(let i=0;i<columns;i+=1){appendCell(row,history[i],side,rackState(own[i],opponent[i],i+1),i+1,name,editable)}body.append(row)}const statusRow=document.createElement('tr');const statusLabel=document.createElement('th');statusLabel.className='row-label';statusLabel.scope='row';statusLabel.textContent='Status';statusRow.append(statusLabel);const mismatches=[];let pending=0;for(let i=0;i<columns;i+=1){const state=rackState(own[i],opponent[i],i+1);appendStatusCell(statusRow,state,i+1);if(state==='mismatch')mismatches.push(i+1);if(state==='pending')pending+=1}body.append(statusRow);setText('[data-ledger-state]',mismatches.length?mismatches.length+' rack'+(mismatches.length===1?'':'s')+' need attention':pending?pending+' pending submission'+(pending===1?'':'s'):'Both sides aligned');requestAnimationFrame(()=>{if(ledgerRestoreLeft!=null){ledgerScroll.scrollLeft=ledgerRestoreLeft;ledgerRestoreLeft=null}else{ledgerScroll.scrollLeft=ledgerScroll.scrollWidth}})}
    function renderScorecard(scorecard){currentScorecard=scorecard;setText('[data-player-a-name]',scorecard.player_a_display_name);setText('[data-player-b-name]',scorecard.player_b_display_name);setText('[data-player-a-rating]',ratingText(scorecard.player_a_fargo_rating,scorecard.player_a_rating_status));setText('[data-player-b-rating]',ratingText(scorecard.player_b_fargo_rating,scorecard.player_b_rating_status));setText('[data-target-a]',scorecard.race_to_a);setText('[data-target-b]',scorecard.race_to_b);setText('[data-race-status]',scorecard.status);setText('[data-detail-break]',sideName(scorecard.first_break));setText('[data-detail-status]',scorecard.status);setText('[data-detail-team]',scoringTeamName);renderOpeningChoice(scorecard.opening_discipline||'8-ball',false)}
    function renderContext(context){currentContext=context||null;if(!context){setText('[data-match-context]','Current player match');return}setText('[data-match-context]','Round '+context.round_number+' • Match '+context.match_number+' of '+context.match_count);setText('[data-team-a-name]',context.team_a_name);setText('[data-team-b-name]',context.team_b_name);setText('[data-team-score-a]',context.team_score_a);setText('[data-team-score-b]',context.team_score_b)}
    function renderComparison(comparison){currentComparison=comparison;const locked=currentScorecard&&['finalized','corrected'].includes(currentScorecard.status);const own=comparison.own_racks||[];const opponent=comparison.opponent_racks||[];const started=own.length>0||opponent.length>0;renderOpeningChoice(currentScorecard?.opening_discipline||'8-ball',locked||started);const score=reconciledScore(comparison);setText('[data-score-a]',score[0]);setText('[data-score-b]',score[1]);renderLedger();const nextRack=own.length+1;setText('[data-next-rack]',nextRack);setText('[data-next-discipline]',gameForRack(nextRack));addRackButton.textContent='Add Rack '+nextRack+' · '+gameForRack(nextRack);rackAButton.textContent=currentScorecard.player_a_display_name+' wins';rackBButton.textContent=currentScorecard.player_b_display_name+' wins';if(comparison.histories_match){reconcileEl.dataset.state='match';setText('[data-reconcile-title]',comparison.both_confirmed?'Scores match · both confirmed':'Scores match');setText('[data-reconcile-detail]',comparison.ready_to_finalize?'Ready to finalize':'Waiting for both confirmations')}else{reconcileEl.dataset.state='mismatch';setText('[data-reconcile-title]',comparison.mismatch_rack_number?'Rack '+comparison.mismatch_rack_number+' needs attention':'Waiting for the other team');setText('[data-reconcile-detail]',comparison.mismatch_rack_number?'Compare the W/L column above':'Both teams keep their own score')}addRackButton.disabled=locked||Boolean(comparison.own_confirmed_at);rackAButton.disabled=addRackButton.disabled;rackBButton.disabled=addRackButton.disabled;undoButton.disabled=locked||Boolean(comparison.own_confirmed_at)||!own.length;confirmButton.disabled=locked||Boolean(comparison.own_confirmed_at)||!own.length;finalizeButton.disabled=locked||!comparison.ready_to_finalize;if(editingRackNumber&&!own[editingRackNumber-1]&&!opponent[editingRackNumber-1])closeRackEditor()}
    async function loadAll({quiet=false}={}){if(!quiet)setStatus('Loading…');const[scoreBody,comparisonBody]=await Promise.all([api('/api/player-matches/:id/scorecard',{method:'GET'}),api('/api/player-matches/:id/score-comparison',{method:'GET'})]);renderScorecard(scoreBody.scorecard);renderContext(comparisonBody.context);renderComparison(comparisonBody.comparison);if(!quiet)setStatus('Live','ok')}
    async function chooseOpeningDiscipline(openingDiscipline){setStatus('Saving game order…');await api('/api/player-matches/:id/score-racks',{method:'POST',body:JSON.stringify({openingDiscipline,scoringTeamId})});await loadAll();setStatus((openingDiscipline==='9-ball'?'9-ball':'8-ball')+' will be played first.','ok')}
    async function recordRack(winner){setStatus('Saving rack…');await api('/api/player-matches/:id/score-racks',{method:'POST',body:JSON.stringify({winnerSide:winner,scoringTeamId})});winnerPicker.dataset.open='false';await loadAll()}
    async function updateRack(rackNumber,result){const side=trackerSide();const winner=result==='W'?side:oppositeSide(side);const own=currentComparison?.own_racks||[];const existing=Boolean(own[rackNumber-1]);ledgerRestoreLeft=ledgerScroll.scrollLeft;setStatus((existing?'Updating':'Recording')+' rack '+rackNumber+'…');const body=existing?{rackNumber,winnerSide:winner,scoringTeamId}:{winnerSide:winner,scoringTeamId};await api('/api/player-matches/:id/score-racks',{method:'POST',body:JSON.stringify(body)});closeRackEditor();await loadAll();setStatus('Rack '+rackNumber+' '+(existing?'updated':'recorded'),'ok')}
    async function undoRack(){setStatus('Undoing rack…');await api('/api/player-matches/:id/score-racks/undo',{method:'POST',body:JSON.stringify({scoringTeamId})});await loadAll()}
    async function confirmScore(){setStatus('Confirming score…');await api('/api/player-matches/:id/score-confirm',{method:'POST',body:JSON.stringify({scoringTeamId})});await loadAll()}
    async function finalizeMatch(){setStatus('Finalizing match…');await api('/api/player-matches/:id/finalize-reconciled',{method:'POST',body:JSON.stringify({scoringTeamId})});await loadAll();setStatus('Finalized','ok')}
    function openRackEditor(number){if(!currentComparison||!currentScorecard)return;const own=currentComparison.own_racks||[];const opponent=currentComparison.opponent_racks||[];const ownRack=own[number-1];const opponentRack=opponent[number-1];const answeringPending=!ownRack&&Boolean(opponentRack)&&number===own.length+1;if((!ownRack&&!answeringPending)||currentComparison.own_confirmed_at||['finalized','corrected'].includes(currentScorecard.status))return;editingRackNumber=number;const side=trackerSide();const otherSide=oppositeSide(side);setText('[data-edit-rack-number]',number);setText('[data-edit-discipline]',gameForRack(number));setText('[data-edit-own-label]',sideName(side)+' · your team');setText('[data-edit-own-value]',cellValue(ownRack,side));setText('[data-edit-opponent-label]',sideName(otherSide)+' · other team');setText('[data-edit-opponent-value]',cellValue(opponentRack,otherSide));for(const button of editResultButtons)button.setAttribute('aria-pressed',String(Boolean(ownRack)&&button.dataset.editResult===cellValue(ownRack,side)));editPanel.hidden=false;editPanel.scrollIntoView({block:'nearest',behavior:'smooth'})}
    function closeRackEditor(){editingRackNumber=null;editPanel.hidden=true}
    async function run(action){try{await action()}catch(error){const remoteChange=error.message.includes('Score changed on another device')||error.message.includes('Refresh the scorecard before changing the score');if(remoteChange){closeRackEditor();winnerPicker.dataset.open='false';try{await loadAll({quiet:true})}catch{}setStatus('Score refreshed','ok');showError('Score changed on another phone. We refreshed it—check the current rack before scoring.');return}setStatus('Action failed','error');showError(error.message)}}
    function startRefresh(){clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(document.visibilityState==='visible'&&matchId&&scoringTeamId&&accessToken()&&!editingRackNumber)run(()=>loadAll({quiet:true}))},3000)}
    for(const button of openingButtons)button.addEventListener('click',()=>run(()=>chooseOpeningDiscipline(button.dataset.opening)));
    addRackButton.addEventListener('click',()=>{winnerPicker.dataset.open=winnerPicker.dataset.open==='true'?'false':'true'});
    rackAButton.addEventListener('click',()=>run(()=>recordRack('A')));rackBButton.addEventListener('click',()=>run(()=>recordRack('B')));
    ledger.addEventListener('click',(event)=>{const button=event.target.closest('[data-edit-rack]');if(button)openRackEditor(Number(button.dataset.editRack))});
    editClose.addEventListener('click',closeRackEditor);for(const button of editResultButtons)button.addEventListener('click',()=>{if(editingRackNumber)run(()=>updateRack(editingRackNumber,button.dataset.editResult))});
    undoButton.addEventListener('click',()=>run(undoRack));confirmButton.addEventListener('click',()=>run(confirmScore));finalizeButton.addEventListener('click',()=>run(finalizeMatch));
    if(!matchId||!scoringTeamId){setStatus('Choose a match and scoring team from the scorecard list.','error');for(const button of [...openingButtons,addRackButton,rackAButton,rackBButton,undoButton,confirmButton,finalizeButton])button.disabled=true}else if(!accessToken()){setStatus('Sign in with Google to score this match.','error');for(const button of [...openingButtons,addRackButton,rackAButton,rackBButton,undoButton,confirmButton,finalizeButton])button.disabled=true;document.querySelector('[data-match-context]').innerHTML='<a href="/profile">Open Profile to sign in</a>'}else{run(loadAll);startRefresh()}
  </script>
</body>
</html>`;
}
