export function renderScorecardPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Fremont Derby Scorecard</title>
  <style>
    :root { color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui, sans-serif; background:#111313; color:#f6f1e7; --panel:#1a1d1d; --line:#343a3a; --muted:#a9b2ae; --green:#2fa56f; --gold:#d7a934; --red:#d55448; --blue:#4b83d8; }
    * { box-sizing:border-box; } body { margin:0; min-height:100vh; background:#111313; } button { font:inherit; }
    button { min-height:44px; border:1px solid transparent; border-radius:8px; color:#0d1110; font-weight:800; cursor:pointer; } button:disabled { cursor:not-allowed; opacity:.45; }
    .app { width:min(960px,100%); margin:0 auto; padding:16px; } .topbar { display:flex; align-items:center; justify-content:space-between; gap:12px; padding:6px 0 14px; border-bottom:1px solid var(--line); }
    .brand { display:flex; align-items:center; gap:10px; font-weight:900; } .balls { display:flex; gap:4px; } .ball { width:28px; height:28px; border-radius:50%; display:grid; place-items:center; color:#12120f; background:#f7f4eb; font-size:.85rem; font-weight:900; } .ball.nine { background:linear-gradient(#e2b737 0 34%,#f7f4eb 34% 66%,#e2b737 66%); }
    .status { min-height:32px; display:flex; align-items:center; justify-content:flex-end; color:var(--muted); font-size:.9rem; text-align:right; } .status[data-tone="error"] { color:#ffb1aa; } .status[data-tone="ok"] { color:#9ee5bd; }
    .context { display:flex; justify-content:space-between; align-items:center; gap:12px; padding:12px 0; border-bottom:1px solid var(--line); color:var(--muted); font-size:.9rem; }
    .context a { color:#f6df9d; font-weight:900; text-decoration:none; }
    .summary,.histories { display:grid; grid-template-columns:minmax(0,1fr) minmax(0,1fr); gap:12px; padding:14px 0; } .player,.history { border:1px solid var(--line); border-radius:8px; background:var(--panel); padding:14px; display:grid; gap:12px; }
    .player[data-side="A"] { border-top:4px solid var(--green); } .player[data-side="B"] { border-top:4px solid var(--blue); } .player-head { display:flex; justify-content:space-between; gap:10px; align-items:start; } .name { margin:0; font-size:1.25rem; line-height:1.15; } .meta { color:var(--muted); font-size:.9rem; }
    .score-row { display:flex; align-items:baseline; justify-content:space-between; gap:10px; } .score { font-size:4rem; line-height:1; font-weight:950; } .race { color:var(--gold); font-weight:900; }
    .rack-action { width:100%; } .rack-action[data-side="A"] { background:var(--green); color:#06120d; } .rack-action[data-side="B"] { background:var(--blue); color:#07101f; }
    .match-bar { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:10px; padding:12px; border:1px solid var(--line); border-radius:8px; background:#151818; } .stat { display:grid; gap:4px; min-width:0; } .stat span { color:var(--muted); font-size:.75rem; font-weight:800; } .stat strong { overflow-wrap:anywhere; }
    .reconcile { margin:14px 0 0; padding:14px; border:1px solid var(--line); border-radius:8px; background:#151818; display:grid; gap:8px; } .reconcile[data-state="match"] { border-color:var(--green); } .reconcile[data-state="mismatch"] { border-color:var(--red); } .reconcile strong { font-size:1.05rem; }
    .actions { display:grid; grid-template-columns:1fr 1fr 1fr; gap:10px; padding:14px 0; } .undo { background:transparent; color:#f6f1e7; border-color:var(--line); } .confirm { background:var(--gold); } .finalize { background:var(--red); color:#1a0604; }
    .racks { border:1px solid var(--line); border-radius:8px; overflow:hidden; } .rack-row { min-height:42px; display:grid; grid-template-columns:64px 1fr 1fr; gap:8px; align-items:center; padding:0 12px; border-bottom:1px solid var(--line); background:#151818; } .rack-row:last-child { border-bottom:0; } .rack-row[data-mismatch="true"] { background:#341b19; } .rack-head { color:var(--muted); font-size:.75rem; font-weight:900; text-transform:uppercase; } .empty { padding:16px; color:var(--muted); background:#151818; }
    .history h3 { margin:0; } .history-state { font-size:.85rem; color:var(--muted); }
    @media (max-width:720px) { .app { padding:12px; } .topbar,.context { align-items:flex-start; } .context { display:grid; } .summary,.histories,.match-bar,.actions { grid-template-columns:1fr; } .score { font-size:3.5rem; } .status { justify-content:flex-start; text-align:left; } }
  </style>
</head>
<body>
  <main class="app">
    <header class="topbar"><div class="brand"><span class="balls" aria-hidden="true"><span class="ball">8</span><span class="ball nine">9</span></span><span>Fremont Derby Scorecard</span></div><div class="status" data-status>Loading…</div></header>
    <div class="context"><span data-context>Using your signed-in team scoring session.</span><a href="/scorecard">Choose another match</a></div>
    <section class="summary" aria-live="polite">
      <article class="player" data-side="A"><div class="player-head"><div><h2 class="name" data-player-a-name>Player A</h2><div class="meta" data-player-a-rating>Rating</div></div><div class="race" data-player-a-race>Race to -</div></div><div class="score-row"><span class="score" data-score-a>0</span><span class="meta">canonical</span></div><button class="rack-action" data-rack-a data-side="A" type="button">A wins rack</button></article>
      <article class="player" data-side="B"><div class="player-head"><div><h2 class="name" data-player-b-name>Player B</h2><div class="meta" data-player-b-rating>Rating</div></div><div class="race" data-player-b-race>Race to -</div></div><div class="score-row"><span class="score" data-score-b>0</span><span class="meta">canonical</span></div><button class="rack-action" data-rack-b data-side="B" type="button">B wins rack</button></article>
    </section>
    <section class="match-bar"><div class="stat"><span>Discipline</span><strong data-discipline>-</strong></div><div class="stat"><span>First break</span><strong data-break>-</strong></div><div class="stat"><span>Status</span><strong data-match-status>-</strong></div><div class="stat"><span>Winner</span><strong data-winner>-</strong></div></section>
    <section class="reconcile" data-reconcile><strong data-reconcile-title>Loading both score records…</strong><span class="meta" data-reconcile-detail></span></section>
    <section class="actions"><button class="undo" data-undo type="button">Undo my latest rack</button><button class="confirm" data-confirm type="button">Confirm my score</button><button class="finalize" data-finalize type="button">Finalize reconciled match</button></section>
    <section class="histories"><article class="history"><h3>My rack history</h3><div class="history-state" data-own-state>Not loaded</div><div class="racks" data-own-racks><div class="empty">No rack history loaded.</div></div></article><article class="history"><h3>Opponent rack history</h3><div class="history-state" data-opponent-state>Not loaded</div><div class="racks" data-opponent-racks><div class="empty">No rack history loaded.</div></div></article></section>
  </main>
  <script>
    const params=new URLSearchParams(location.search); const matchId=params.get('match')||''; const statusEl=document.querySelector('[data-status]'); const rackAButton=document.querySelector('[data-rack-a]'); const rackBButton=document.querySelector('[data-rack-b]'); const undoButton=document.querySelector('[data-undo]'); const confirmButton=document.querySelector('[data-confirm]'); const finalizeButton=document.querySelector('[data-finalize]');
    const ownRacksEl=document.querySelector('[data-own-racks]'); const opponentRacksEl=document.querySelector('[data-opponent-racks]'); const reconcileEl=document.querySelector('[data-reconcile]'); let currentScorecard=null; let currentComparison=null; let refreshTimer=null;
    function accessToken(){return sessionStorage.getItem('fd.accessToken')||'';}
    function setStatus(message,tone){statusEl.textContent=message; statusEl.dataset.tone=tone||'muted';}
    function requireContext(){const token=accessToken(); if(!matchId) throw new Error('Choose a match from the scorecard list.'); if(!token) throw new Error('Sign in with Google to score this match.'); return {matchId,token};}
    async function api(path,options={}){const inputs=requireContext(); const response=await fetch(path.replace(':id',encodeURIComponent(inputs.matchId)),{...options,headers:{authorization:'Bearer '+inputs.token,'content-type':'application/json',...(options.headers||{})}}); const body=await response.json(); if(response.status===401){sessionStorage.removeItem('fd.accessToken'); throw new Error('Your sign-in expired. Open Profile and sign in again.');} if(!response.ok) throw new Error(body.error||'Request failed'); return body;}
    function sideLabel(side){if(!currentScorecard) return side; return side==='A'?currentScorecard.player_a_display_name:currentScorecard.player_b_display_name;}
    function ratingText(rating,status){return [rating||'Unrated',status||'unverified'].join(' | ');} function setText(selector,value){document.querySelector(selector).textContent=value==null||value===''?'-':String(value);}
    function renderRacks(target,racks,mismatchRack){target.replaceChildren(); if(!racks||!racks.length){const empty=document.createElement('div'); empty.className='empty'; empty.textContent='No racks recorded.'; target.append(empty); return;} const head=document.createElement('div'); head.className='rack-row rack-head'; head.innerHTML='<span>Rack</span><span>Winner</span><span>Discipline</span>'; target.append(head); for(const rack of racks){const number=rack.rackNumber||rack.rack_number; const row=document.createElement('div'); row.className='rack-row'; if(Number(number)===Number(mismatchRack)) row.dataset.mismatch='true'; const n=document.createElement('span'); n.textContent=number; const winner=document.createElement('strong'); winner.textContent=sideLabel(rack.winnerSide||rack.winner_side); const discipline=document.createElement('span'); discipline.textContent=rack.discipline; row.append(n,winner,discipline); target.append(row);}}
    function renderScorecard(scorecard){currentScorecard=scorecard; setText('[data-player-a-name]',scorecard.player_a_display_name); setText('[data-player-b-name]',scorecard.player_b_display_name); setText('[data-player-a-rating]',ratingText(scorecard.player_a_fargo_rating,scorecard.player_a_rating_status)); setText('[data-player-b-rating]',ratingText(scorecard.player_b_fargo_rating,scorecard.player_b_rating_status)); setText('[data-player-a-race]','Race to '+(scorecard.race_to_a||'-')); setText('[data-player-b-race]','Race to '+(scorecard.race_to_b||'-')); setText('[data-score-a]',scorecard.score_a); setText('[data-score-b]',scorecard.score_b); setText('[data-discipline]',scorecard.current_discipline); setText('[data-break]',scorecard.first_break); setText('[data-match-status]',scorecard.status); setText('[data-winner]',scorecard.winner_side?sideLabel(scorecard.winner_side):'-'); rackAButton.textContent=scorecard.player_a_display_name+' wins rack'; rackBButton.textContent=scorecard.player_b_display_name+' wins rack'; document.querySelector('[data-context]').textContent=scorecard.player_a_display_name+' vs '+scorecard.player_b_display_name;}
    function renderComparison(comparison){currentComparison=comparison; const locked=currentScorecard&&['finalized','corrected'].includes(currentScorecard.status); const mismatch=comparison.mismatch_rack_number; renderRacks(ownRacksEl,comparison.own_racks||[],mismatch); renderRacks(opponentRacksEl,comparison.opponent_racks||[],mismatch); document.querySelector('[data-own-state]').textContent=comparison.own_confirmed_at?'Confirmed':'Not confirmed'; document.querySelector('[data-opponent-state]').textContent=comparison.opponent_confirmed_at?'Confirmed':'Not confirmed'; if(comparison.histories_match){reconcileEl.dataset.state='match'; setText('[data-reconcile-title]',comparison.both_confirmed?'Scores match and both teams confirmed.':'Scores match. Waiting for both confirmations.'); setText('[data-reconcile-detail]',comparison.ready_to_finalize?'Ready to finalize.':'Both teams must confirm before finalization.');}else{reconcileEl.dataset.state='mismatch'; setText('[data-reconcile-title]',mismatch?'Score mismatch at rack '+mismatch+'.':'Waiting for both teams to record the same completed score.'); setText('[data-reconcile-detail]','Each team can edit only its own rack history.');} rackAButton.disabled=locked||Boolean(comparison.own_confirmed_at); rackBButton.disabled=locked||Boolean(comparison.own_confirmed_at); undoButton.disabled=locked||Boolean(comparison.own_confirmed_at)||!(comparison.own_racks&&comparison.own_racks.length); confirmButton.disabled=locked||Boolean(comparison.own_confirmed_at)||!(comparison.own_racks&&comparison.own_racks.length); finalizeButton.disabled=locked||!comparison.ready_to_finalize;}
    async function loadAll({quiet=false}={}){if(!quiet) setStatus('Loading...'); const [scoreBody,comparisonBody]=await Promise.all([api('/api/player-matches/:id/scorecard',{method:'GET'}),api('/api/player-matches/:id/score-comparison',{method:'GET'})]); renderScorecard(scoreBody.scorecard); renderComparison(comparisonBody.comparison); if(!quiet) setStatus('Dual scorecard loaded','ok');}
    async function recordRack(winnerSide){setStatus('Recording my rack...'); await api('/api/player-matches/:id/score-racks',{method:'POST',body:JSON.stringify({winnerSide})}); await loadAll();}
    async function undoRack(){setStatus('Undoing my latest rack...'); await api('/api/player-matches/:id/score-racks/undo',{method:'POST',body:'{}'}); await loadAll();}
    async function confirmScore(){setStatus('Confirming my score...'); await api('/api/player-matches/:id/score-confirm',{method:'POST',body:'{}'}); await loadAll();}
    async function finalizeMatch(){setStatus('Finalizing reconciled match...'); await api('/api/player-matches/:id/finalize-reconciled',{method:'POST',body:'{}'}); await loadAll(); setStatus('Match finalized','ok');}
    async function run(action){try{await action();}catch(error){setStatus(error.message,'error');}}
    function startRefresh(){clearInterval(refreshTimer); refreshTimer=setInterval(()=>{if(document.visibilityState==='visible'&&matchId&&accessToken()) run(()=>loadAll({quiet:true}));},3000);}
    rackAButton.addEventListener('click',()=>run(()=>recordRack('A'))); rackBButton.addEventListener('click',()=>run(()=>recordRack('B'))); undoButton.addEventListener('click',()=>run(undoRack)); confirmButton.addEventListener('click',()=>run(confirmScore)); finalizeButton.addEventListener('click',()=>run(finalizeMatch));
    if(!matchId){setStatus('Choose a match from the scorecard list.','error'); rackAButton.disabled=true; rackBButton.disabled=true; undoButton.disabled=true; confirmButton.disabled=true; finalizeButton.disabled=true;} else if(!accessToken()){setStatus('Sign in with Google to score this match.','error'); const context=document.querySelector('[data-context]'); context.innerHTML='<a href="/profile">Open Profile to sign in</a>';} else {run(loadAll); startRefresh();}
  </script>
</body>
</html>`;
}
