export function renderScorePickerPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Score a Match · Fremont Derby</title>
  <style>
    :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#111313;color:#f6f1e7;--panel:#1a1d1d;--line:#343a3a;--muted:#a9b2ae;--green:#2fa56f;--gold:#d7a934}*{box-sizing:border-box}body{margin:0;background:#111313}.app{width:min(760px,100%);margin:auto;padding:16px}.head{padding:8px 0 16px;border-bottom:1px solid var(--line)}h1{margin:0 0 8px;font-size:clamp(2rem,8vw,3.4rem);line-height:1}.muted{color:var(--muted);line-height:1.45}.filters{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0;padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--panel)}.filters[hidden]{display:none}.filters label{display:grid;gap:6px;color:var(--muted);font-size:.78rem;font-weight:850}.filters select{width:100%;min-height:46px;border:1px solid var(--line);border-radius:10px;background:#111716;color:#f6f1e7;padding:0 11px;font:inherit}.filters select:focus-visible{outline:3px solid #f4d46d;outline-offset:2px}.status{margin:14px 0;padding:12px;border:1px solid var(--line);border-radius:10px;background:var(--panel)}.status[data-tone="error"]{border-color:#a84940;color:#ffb1aa}.status[data-tone="ready"]{border-color:#3a7554;color:#b8e8cb}.list{display:grid;gap:10px}.match{display:grid;gap:9px;padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--panel);text-decoration:none;color:#f6f1e7}.match:hover{border-color:#52765f}.match:focus-visible,.button:focus-visible{outline:3px solid #f4d46d;outline-offset:3px}.top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.players{font-size:1.06rem;font-weight:900}.teams,.meta{color:var(--muted);font-size:.88rem}.side{display:inline-flex;align-items:center;min-height:26px;padding:0 9px;border-radius:999px;background:#193b2a;color:#a7e8c2;font-size:.75rem;font-weight:900;white-space:nowrap}.empty{display:grid;gap:10px;padding:22px 16px;border:1px solid var(--line);border-radius:14px;background:linear-gradient(145deg,#1b211e,#171a19);box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}.empty strong{font-size:1.1rem}.empty p{margin:0;color:var(--muted);line-height:1.5}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:3px}.button{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:10px 15px;border:1px solid transparent;border-radius:10px;background:var(--gold);color:#17120a;text-decoration:none;font-weight:900}.button.secondary{border-color:var(--line);background:#232827;color:#f6f1e7}@media(max-width:600px){.app{padding:12px}.filters{grid-template-columns:1fr}.top{display:grid}.side{justify-self:start}.actions{display:grid;grid-template-columns:1fr}.button{width:100%}}
  </style>
</head>
<body>
  <main class="app">
    <header class="head"><h1>Score a match</h1><div class="muted">Start with today, then switch dates, teams, matchups, or revealed races when you need a makeup, early match, or another authorized race. Captains can prepare the blind three here before scoring opens. No tokens or database IDs required.</div></header>
    <section class="filters" aria-label="Score context" data-filters hidden>
      <label>Date<select data-date aria-label="Score date"></select></label>
      <label>Team<select data-team aria-label="Scoring team"></select></label>
      <label>Matchup<select data-matchup aria-label="Team matchup"></select></label>
      <label>Race<select data-race aria-label="Revealed race"></select></label>
    </section>
    <div class="status" role="status" aria-live="polite" data-status>Loading your matches…</div>
    <section class="list" aria-label="Selected race available to score" data-list></section>
  </main>
  <script>
    const statusEl=document.querySelector('[data-status]');const listEl=document.querySelector('[data-list]');const filtersEl=document.querySelector('[data-filters]');const dateSelect=document.querySelector('[data-date]');const teamSelect=document.querySelector('[data-team]');const matchupSelect=document.querySelector('[data-matchup]');const raceSelect=document.querySelector('[data-race]');let matches=[];let captainContexts=[];
    function token(){return sessionStorage.getItem('fd.accessToken')||''}
    function setStatus(message,tone){statusEl.textContent=message;statusEl.dataset.tone=tone||'muted'}
    function text(value){return value==null?'':String(value)}
    function localDateKey(){const now=new Date();const year=now.getFullYear();const month=String(now.getMonth()+1).padStart(2,'0');const day=String(now.getDate()).padStart(2,'0');return year+'-'+month+'-'+day}
    function dateLabel(value){if(!value||value==='tbd')return'Date TBD';const d=new Date(value+'T12:00:00');return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(d)}
    function actionLink(label,href,secondary=false){const link=document.createElement('a');link.className='button'+(secondary?' secondary':'');link.href=href;link.textContent=label;return link}
    function emptyState(title,detail,actions=[]){const card=document.createElement('div');card.className='empty';const heading=document.createElement('strong');heading.textContent=title;const copy=document.createElement('p');copy.textContent=detail;card.append(heading,copy);if(actions.length){const actionRow=document.createElement('div');actionRow.className='actions';actionRow.append(...actions);card.append(actionRow)}listEl.replaceChildren(card)}
    function liveHref(match){return'/scorecard/live?match='+encodeURIComponent(match.player_match_id)+'&team='+encodeURIComponent(match.scoring_team_id)+'&teamName='+encodeURIComponent(match.scoring_team_name||'Your team')}
    function lineupHref(context){return'/lineup?team='+encodeURIComponent(context.teamId)+'&round='+encodeURIComponent(context.roundId)}
    function matchCard(match){const a=document.createElement('a');a.className='match';a.href=liveHref(match);const top=document.createElement('div');top.className='top';const left=document.createElement('div');const players=document.createElement('div');players.className='players';players.textContent=text(match.player_a_name)+' vs '+text(match.player_b_name);const teams=document.createElement('div');teams.className='teams';teams.textContent=text(match.team_a_name)+' vs '+text(match.team_b_name);left.append(players,teams);const side=document.createElement('span');side.className='side';side.textContent='Scoring for '+text(match.scoring_team_name);top.append(left,side);const meta=document.createElement('div');meta.className='meta';meta.textContent=dateLabel(match.scheduled_on)+' · Round '+text(match.round_number)+' · Pairing '+text(match.slot_number)+' · '+text(match.status);a.append(top,meta);return a}
    function addOption(select,value,label){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option)}
    function baseMatches(){const selectedDate=dateSelect.value;const selectedTeam=teamSelect.value;return matches.filter(match=>(match.scheduled_on||'tbd')===selectedDate).filter(match=>selectedTeam==='all'||text(match.scoring_team_id)===selectedTeam)}
    function baseCaptainContexts(){const selectedDate=dateSelect.value;const selectedTeam=teamSelect.value;return captainContexts.filter(context=>(context.scheduledOn||'tbd')===selectedDate).filter(context=>selectedTeam==='all'||text(context.teamId)===selectedTeam)}
    function matchupLabel(match){return text(match.team_a_name)+' vs '+text(match.team_b_name)+' · Round '+text(match.round_number)}
    function captainMatchupLabel(context){return text(context.teamName)+' vs '+text(context.opponentName)+' · Round '+text(context.roundNumber)}
    function raceLabel(match){return'Pairing '+text(match.slot_number)+' · '+text(match.player_a_name)+' vs '+text(match.player_b_name)}
    function selectedCaptainContext(){const matchupId=matchupSelect.value;return baseCaptainContexts().find(context=>text(context.teamMatchId)===matchupId)||null}
    function populateMatchups(){const previous=matchupSelect.value;matchupSelect.replaceChildren();const seen=new Set();for(const match of baseMatches()){const id=text(match.team_match_id);if(!id||seen.has(id))continue;seen.add(id);addOption(matchupSelect,id,matchupLabel(match))}for(const context of baseCaptainContexts()){const id=text(context.teamMatchId);if(!id||seen.has(id))continue;seen.add(id);addOption(matchupSelect,id,captainMatchupLabel(context))}if(previous&&seen.has(previous))matchupSelect.value=previous;populateRaces()}
    function populateRaces(){const previous=raceSelect.value;raceSelect.replaceChildren();const matchupId=matchupSelect.value;const races=baseMatches().filter(match=>text(match.team_match_id)===matchupId);for(const match of races)addOption(raceSelect,text(match.player_match_id),raceLabel(match));if(previous&&races.some(match=>text(match.player_match_id)===previous))raceSelect.value=previous;renderSelection()}
    function addDateKey(keys,key,today){if(key&&key!==today&&!keys.includes(key))keys.push(key)}
    function addTeamChoice(seen,id,name){if(!id||seen.has(id))return;seen.add(id);addOption(teamSelect,id,name||'My team')}
    function populateFilters(){const today=localDateKey();dateSelect.replaceChildren();addOption(dateSelect,today,'Today · '+dateLabel(today));const dates=[];for(const match of matches)addDateKey(dates,match.scheduled_on||'tbd',today);for(const context of captainContexts)addDateKey(dates,context.scheduledOn||'tbd',today);for(const key of dates)addOption(dateSelect,key,dateLabel(key));teamSelect.replaceChildren();addOption(teamSelect,'all','All my teams');const seen=new Set();for(const match of matches)addTeamChoice(seen,text(match.scoring_team_id),text(match.scoring_team_name));for(const context of captainContexts)addTeamChoice(seen,text(context.teamId),text(context.teamName));filtersEl.hidden=false;populateMatchups()}
    function renderCaptainPrep(context){raceSelect.disabled=true;setStatus('This matchup is not ready to score yet. You can prepare the blind three now.');emptyState('Prepare your lineup',captainMatchupLabel(context)+' is scheduled. Open the existing lineup workflow to see dated availability, find substitutes, and lock your three. Opponent order stays hidden until both teams submit.',[actionLink('Prepare lineup',lineupHref(context)),actionLink('Open Schedule','/schedule',true)])}
    function renderSelection(){const visible=baseMatches();const captainVisible=baseCaptainContexts();listEl.replaceChildren();if(!visible.length&&!captainVisible.length){setStatus('No scoring options for '+dateLabel(dateSelect.value)+'.');emptyState('Nothing ready for this selection','Choose another date or team above. If you are waiting on a lineup reveal, check Schedule.',[actionLink('Open Schedule','/schedule'),actionLink('Check my team','/teams',true)]);matchupSelect.disabled=true;raceSelect.disabled=true;return}matchupSelect.disabled=false;const matchupId=matchupSelect.value;const races=visible.filter(match=>text(match.team_match_id)===matchupId);if(!races.length){const captainContext=selectedCaptainContext();if(captainContext){renderCaptainPrep(captainContext);return}raceSelect.disabled=true;setStatus('No revealed races for this matchup yet.');emptyState('Waiting on lineup reveal','The matchup is scheduled, but there is no revealed race available to score for this selection.',[actionLink('Open Schedule','/schedule')]);return}raceSelect.disabled=false;const selected=races.find(match=>text(match.player_match_id)===raceSelect.value)||races[0];if(!selected)return;raceSelect.value=text(selected.player_match_id);listEl.append(matchCard(selected));setStatus(races.length+' fixed pairing'+(races.length===1?'':'s')+' revealed. Choose any pairing to score next.','ready')}
    function flattenCaptainContexts(body){const teams=body?.teamManagement?.captain_teams||[];const contexts=[];for(const team of teams){for(const round of team.lineupRounds||[]){contexts.push({...round,teamId:team.teamId,teamName:team.teamName,seasonId:team.seasonId,seasonName:team.seasonName})}}return contexts}
    async function load(){const accessToken=token();if(!accessToken){setStatus('Sign in to see matches your team can score.');emptyState('Ready when your team is','Sign in with Google and we will show only the matches your team is allowed to score.',[actionLink('Sign in to score','/profile'),actionLink('Open Schedule','/schedule',true)]);return}try{const scorePromise=fetch('/api/me/scorable-matches',{headers:{authorization:'Bearer '+accessToken}});const teamPromise=fetch('/api/me/teams',{headers:{authorization:'Bearer '+accessToken}}).then(async response=>response.ok?response.json():null).catch(()=>null);const [response,teamBody]=await Promise.all([scorePromise,teamPromise]);const body=await response.json();if(response.status===401){sessionStorage.removeItem('fd.accessToken');setStatus('Your sign-in expired. Sign in again to continue.','error');emptyState('Sign in again','Your session ended before we could load your scoring options. No score was changed.',[actionLink('Open Profile to sign in','/profile'),actionLink('Open Schedule','/schedule',true)]);return}if(!response.ok)throw new Error(body.error||'Could not load matches');matches=body.matches||[];captainContexts=flattenCaptainContexts(teamBody);listEl.replaceChildren();if(!matches.length&&!captainContexts.length){setStatus('No match is ready to score yet.');emptyState('Nothing ready to score','Your team may still be waiting on lineups or matchup reveal. Check Schedule first; if your team is missing, review your team status.',[actionLink('Open Schedule','/schedule'),actionLink('Check my team','/teams',true)]);return}populateFilters()}catch(error){setStatus('We could not load your scoring options.','error');emptyState('Could not load matches','Nothing was changed. Try again, or open Profile if you need to refresh your sign-in.',[actionLink('Try again','/scorecard'),actionLink('Open Profile','/profile',true)])}}dateSelect.addEventListener('change',populateMatchups);teamSelect.addEventListener('change',populateMatchups);matchupSelect.addEventListener('change',populateRaces);raceSelect.addEventListener('change',renderSelection);load();
  </script>
</body>
</html>`;
}
